### ISSUE TITLE
I can't create mobile dashboard

### ISSUE THREAD

**Issue by whogarden** [blynkkk/beta#101]
I Made a transfer of a device that was OK
![Transfer](https://user-images.githubusercontent.com/16666934/119963858-dd1cdf80-bfa8-11eb-91ff-387c9a4fa326.jpg)

But I can't install Blynk app on the smartphone because emails are not the same.
The email to use with the device transfered in web "https://blynk.cloud/dashboard/xxx" 
 is not the same as the email in the (android) smartphone.
How can I change the email to use with the smartphone?

**Comment by doom369** [comment]
Sorry I don't understand you. Could you please use some example. Like "I'm logged under X, did transfer to Y, etc"

**Comment by whogarden** [comment]
I am logged under the email xxxxx@lapxxxte.fr of the device tranfered 
And I want to  "install Blynk app for android on a smartphone but the email xxxxx@gmail.com is not the loggin email of the web dashboard
![logged](https://user-images.githubusercontent.com/16666934/119988739-b5d50b00-bfc6-11eb-9e7e-2ff81cdc7ee9.jpg)
May be there is something I don't understand.

**Comment by doom369** [comment]
And xxxxx@gmail.com  is the account you was originally logged under, correct? And from xxxxx@gmail.com you did a transfer, right?

**Comment by whogarden** [comment]
Yes

**Comment by doom369** [comment]
@whogarden are you sure you did a logout from the previous account?

**Comment by whogarden** [comment]
Yes done now 
and always same email to install app and web loggin

**Comment by whogarden** [comment]
It's a misunderstanding.
I can not use 2 different email addresses in that case.
I installed the app from Play Store and connected with the web dashboard loggin / pass
And all is fine.
