### ISSUE TITLE
Provide STEM option Like Ubidots IoT Platform

### ISSUE THREAD

**Issue by KANAKARAJA407** [blynkkk/beta#102]
Kindly provide STEM Mode like the Ubidots platform. so that users can thoroughly understand the Blynk platform then they may choose a monthly plan or yearly subscription. Still, I am choosing STEM in Ubidots there are no restrictions, and also they provide up to 3 Channels with 4000 data dots in the storage capacity. this is the best solution to understand the complete Blynk IoT Dashboard so my suggestion is to give STEM Mode it is a benefit for students especially since the number of users count also drastically increased dear Blynk Team. Kindly Think of this solution Thank you.

**Comment by doom369** [comment]
Thanks for the proposal. We'll consider this.
By the way, Blynk has a fully free option for 1 device with 255 variables (ubidots has only 20 variables per device).

**Comment by vshymanskyy** [comment]
Blynk already provides a Free plan. We will expand it's capabilities whenever possible
