### ISSUE TITLE
Problems with Location datastream and Map widget

### ISSUE THREAD

**Issue by mikesoniat** [blynkkk/beta#104]
My map widget was working fine on the old app. Now:

**Web**: I setup a datastream "Location" type connected to my MapWidget virtual pin. It connected up automatically when I added a map widget to the web dashboard. Looks good, but no data is being received on my device dashboard.

**New App:** When I add a map widget, the "Location" pin is not showing up as an option. All other V pins are showing up Doubles and Strings.

I tried both: 

WidgetMap myMap(V12);
myMap.location(map_index, latitude, longitude, "value");

and 

Blynk.virtualWrite(V12, map_index, latitude, longitude, "value");

Same result on both.

Any ideas?

**Comment by doom369** [comment]
@mikesoniat when the Location DataStream created you need to set it as raw DS:

![screenshot-blynk-qa com-2021 05 28-20_17_05](https://user-images.githubusercontent.com/1536494/120019928-b931bc00-bff1-11eb-846d-aa6d720dedc1.png)

We will fix it in the next build. So we don't confuse the people.

Real-time updates for the map are not yet implemented. Will be implemented soon as well.

Correct usage would be:

`Blynk.virtualWrite(V12, longitude, latitude);`

**Comment by mikesoniat** [comment]
Thank you for your quick response. BTW, I love the new UI!

**Comment by doom369** [comment]
@mikesoniat thanks! I'll update this ticket when we'll fix the issue. Meanwhile, I updated the doc with additional info on how to update the map:

https://docs.blynk.io/en/web-dashboard/products/dashboard/map#insert-the-data

**Comment by doom369** [comment]
@mikesoniat both issues are fixed. Now new Location DS isRaw == true by default. Also, the map now supports real-time updates. Please let me know if it works as expected. Please reopen if not fixed.

**Comment by mikesoniat** [comment]
I'm not sure if I'm just missing something. The web UI seems to work great, but my Location virtual pin (V12) is still not available on the iOS app. See below:

Datastream
![image](https://user-images.githubusercontent.com/1984428/120213192-8c032a80-c1f8-11eb-870e-f347a2a4ec3c.png)

Web Map Settings
![image](https://user-images.githubusercontent.com/1984428/120213270-9a514680-c1f8-11eb-83e3-1321e364f450.png)

iOS Map Settings
![iOS App Map Settings](https://user-images.githubusercontent.com/1984428/120213522-ebf9d100-c1f8-11eb-9831-1dceedebdb98.png)

**Comment by doom369** [comment]
@eepetrash, please take a look

**Comment by eepetrash** [comment]
Added Location datastream support for Map widget in iOS build 3.1.2(5)
Available now in TestFlight: https://testflight.apple.com/join/x1xZdnzx

**Comment by mikesoniat** [comment]
Works great! Thank you!
