### ISSUE TITLE
mph and psi not available in datastream units

### ISSUE THREAD

**Issue by mikesoniat** [blynkkk/beta#105]
I would like to request you add mph "Miles Per Hour" and psi "Pounds per Square Inch" to the datastream units options.

**Comment by doom369** [comment]
@mikesoniat thanks for the proposal. Will do.

**Comment by Agnetka-qa** [comment]
@doom369 Is it right?
AR: DS units are doubled
![image](https://user-images.githubusercontent.com/65705128/120157681-f23d7c80-c1fb-11eb-89e7-3ce794a8e19c.png)
![image](https://user-images.githubusercontent.com/65705128/120157723-fc5f7b00-c1fb-11eb-9bd2-6e936c2505da.png)

**Comment by doom369** [comment]
@mikesoniat added. Please reopen if not fixed.
