### ISSUE TITLE
Blynk 1.0.0 compilation error: "functional: No such file or directory"

### ISSUE THREAD

**Issue by JAndrassy** [blynkkk/beta#106]
compilation error:
Arduino/libraries/Blynk/src/Blynk/BlynkConsole.h:20:10: fatal error: functional: No such file or directory

Blynk 1.0.0
Arduino IDE 1.8.15
Arduino Uno
Blynk Arduino_Ethernet example

what library is for `<functional>`?

```
In file included from /home/duro/Documents/Arduino/libraries/Blynk/src/Blynk/BlynkApi.h:38:0,
                 from /home/duro/Documents/Arduino/libraries/Blynk/src/BlynkApiArduino.h:14,
                 from /home/duro/Documents/Arduino/libraries/Blynk/src/Adapters/BlynkEthernet.h:24,
                 from /home/duro/Documents/Arduino/libraries/Blynk/src/BlynkSimpleEthernet.h:20,
                 from /home/duro/Documents/Arduino/libraries/Blynk/examples/Boards_Ethernet/Arduino_Ethernet/Arduino_Ethernet.ino:42:
/home/duro/Documents/Arduino/libraries/Blynk/src/Blynk/BlynkConsole.h:20:10: fatal error: functional: No such file or directory
 #include <functional>
          ^~~~~~~~~~~~
compilation terminated.
Using library SPI at version 1.0 in folder: /home/duro/arduino-1.8.15/hardware/arduino/avr/libraries/SPI 
Using library Ethernet at version 2.0.0 in folder: /home/duro/arduino-1.8.15/libraries/Ethernet 
Using library Blynk at version 1.0.0 in folder: /home/duro/Documents/Arduino/libraries/Blynk 
exit status 1
Error compiling for board Arduino Uno.
```

**Comment by vshymanskyy** [comment]
Thanks for reporting. This issue was fixed, available from `master` branch: https://github.com/blynkkk/blynk-library

**Comment by doom369** [comment]
@jandrassy closing due to lack of the feedback.

**Comment by JAndrassy** [comment]
> 
> 
> @jandrassy closing due to lack of the feedback.

sorry, yes, it is alright

**Comment by JAndrassy** [comment]
@vshymanskyy I saw that the fix was commenting out `BLYNK_CONSOLE_USE_LAMBDAS`. but now it is not commented out in master
EDIT: I see the header is now used only in examples for boards with 'functional'

**Comment by vshymanskyy** [comment]
It was fixed by different means.

**Comment by JAndrassy** [comment]
yes, I see, but I would like to try OTA to Arduino Mega for example with WiFi101 shield  and then I will have the error

**Comment by vshymanskyy** [comment]
We do not support OTA for Arduino Mega.

**Comment by JAndrassy** [comment]
> 
> We do not support OTA for Arduino Mega.

your MKR examples use my ArduinoOTA library and that supports classic ATmega with at lest 64kB flash and Optiboot from MegaCore, so the MKR1000 example would work for Mega with WiFi101 shield (Adafruit WINC1500 WiFi Shield)

**Comment by vshymanskyy** [comment]
You can try, but i doubt it will work without tweaking or some black magic.

**Comment by TejRajAdhikari97** [comment]
I am using this library as mentioned above but showing BlynkSimpleStream.h: No such file or directory 
What to do now 
in another_ program no matching function for call to 'BlynkStream::begin(char [33], HardwareSerial&)'

help me to solve this. I am beginner
