### ISSUE TITLE
Web Dashboard Buttons doesn't work

### ISSUE THREAD

**Issue by LucasVS1998** [blynkkk/beta#107]
In web or in the quick button in the app i can't use the functionalities

**Comment by doom369** [comment]
Could you please provide more details? What button do you mean?

**Comment by LucasVS1998** [comment]
![blynk issue](https://user-images.githubusercontent.com/83510012/120210887-aba14f80-c206-11eb-8ba8-007fb36a653c.png)
None of those values is corresponding to the datastream variables, for example...

**Comment by doom369** [comment]
@LucasVS1998 yes, that's a device template, it's not really connected to any device. It just a random values to show you how it will look like on the device.

**Comment by Carlini2016** [comment]
> In web or in the quick button in the app i can't use the functionalities



> In web or in the quick button in the app i can't use the functionalities

E ai Lucas, conseguiu colocar pra funcionar ? Estou testando, mas também não funcionou

**Comment by LucasVS1998** [comment]
Então cara, pelo que eu entendi ali esse Web Dashboard é só um "template", nele você só configura como as coisas vão parecer... A questão é que não sei ainda onde essas variáveis realmente irão estar na web... como acompanhar elas (talvez só com uma atualização futura)

**Comment by Carlini2016** [comment]
Why this Topic was closed ? Someone has a solution ?

**Comment by doom369** [comment]
@Carlini2016 this ticket has no bug desciption. Described issue is not a bug. It's a template, not a device view. So all is correct here.

**Comment by doom369** [comment]
Template view:

![screenshot-blynk-qa com-2021 06 02-14_12_43](https://user-images.githubusercontent.com/1536494/120470786-a251e780-c3ac-11eb-9be8-bc444f0d2215.png)

Real device view:

![screenshot-blynk-qa com-2021 06 02-14_12_18](https://user-images.githubusercontent.com/1536494/120470813-aaaa2280-c3ac-11eb-8245-7da04d0951c2.png)
