### ISSUE TITLE
Text Input - No supported data stream

### ISSUE THREAD

**Issue by cactixxx** [blynkkk/beta#108]
I created an enumerable datastream in Blynk.360 (which is the only stream that make sense), but the App reports there are no supported datasteams for the text input interface.

**Comment by doom369** [comment]
@alexkipar @eepetrash I thought we fixed that one. Please clarify.

**Comment by alexkipar** [comment]
@doom369 text input can't support enum ds

**Comment by alexkipar** [comment]
@cactixxx enum ds currently are supported only by value display and labeled display widgets. Soon we will bring them to image, icon and segmented widgets. Can you clarify how you expected to use it in text input one?

**Comment by cactixxx** [comment]
I would like the ability to send custom string data (that the user entered) from the App to the device.  Currently, there are only Virtual Pin, Enumerable and Location data streams and none of those streams is available to the text input widget.

**Comment by doom369** [comment]
@cactixxx Virtual Datastream has subtypes. There is a String virtual datastream you can use it for this task:
![screenshot-blynk-qa com-2021 06 02-14_15_57](https://user-images.githubusercontent.com/1536494/120471218-1e4c2f80-c3ad-11eb-8d03-2eda1d850904.png)

**Comment by cactixxx** [comment]
Thanks, can't believe we missed it

**Comment by doom369** [comment]
No problem. Glad to help.
