### ISSUE TITLE
xxxxx has transferred Temp logger 95693 to your account.

### ISSUE THREAD

**Issue by whogarden** [blynkkk/beta#109]
In "docs.blynk.io/en/web-dashboard/devices-1" you say "here you can change Device Owner by providing Email of a new one."
I transfer a device to an existing account.
The transfers" seems OK.
The new owner receive the message "xxxxx has transferred Temp logger 95693 to your account."
the device is seen in the original dashboard with the new owner (OK)
but is not présent in de destination dashboard.

**Comment by doom369** [comment]
@whogarden hello. What do you mean by "original dashboard" and "destination dashboard"?

**Comment by whogarden** [comment]
The original dashboard is the user device from where I want to make the transfer.
and the destination is the other user where the device transfered will be used.
No easy to explain

**Comment by whogarden** [comment]
The web dashboard where the device must be transfered is empty.

**Comment by doom369** [comment]
I see. Yes, this should be fixed after we implement template publishing.
