### ISSUE TITLE
Need a better way of deleting a Datastream

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#11]
Currently, the only way to delete a Datastream is to scroll to the far right of the Datastreams grid view and click the trashcan icon in the 'Actions' column). The trashcan icon isn't even visible until you hover over the place where the icon should be.

 I think we need a DELETE option in the Datastream edit dialogue.

The main problem though is that when a Datastream has been edited, the template screen shows the options of Delete, Cancel and Save.

![image](https://user-images.githubusercontent.com/35718564/112721230-bab00c80-8efa-11eb-8b77-7b3d20d99001.png)

I assumed that this Delete option would delete the Datastream that I'd just edited, and the "Are you sure" dialogue mentions Datastreams being removed...

![image](https://user-images.githubusercontent.com/35718564/112721271-e501ca00-8efa-11eb-9bc9-82400efafb0c.png)

What it doesn't say is "**This will delete your template!**", which of course is exactly what it does do!

Pete.

**Comment by alexkipar** [comment]
@Peterkn2001 there is a delete button at the end of the data stream row

**Comment by Peterkn2001** [comment]
> @Peterkn2001 there is a delete button at the end of the data stream row

Yes, that’s why I said...
`Currently, the only way to delete a Datastream is to scroll to the far right of the Datastreams grid view and click the trashcan icon in the 'Actions' column). The trashcan icon isn't even visible until you hover over the place where the icon should be.`

however, it’s not easy to find, especially as the trash can icon is invisible until you hover over it.

Just trying to provide constructive feedback on issues that I find to be confusing or difficult to find.

Pete.

**Comment by alexkipar** [comment]
@Peterkn2001 got it, I thought 'far right' meant top one button. yes, you are right that delete option should be presented better

**Comment by doom369** [comment]
Agree, especially regarding the popup message.

**Comment by Peterkn2001** [comment]
A bit more on this....
I've noticed that in the "My Devices" table view, the "Actions" column is pinned at the right hand side of the screen, so it's always visible.

![image](https://user-images.githubusercontent.com/35718564/112859866-2933cc80-90ab-11eb-8f4e-c273ebdb313f.png)


I think the same thing is needed in the Template / Datastreams view.

Pete.

**Comment by doom369** [comment]
@Peterkn2001 it's also pinned in the datastream section. Isn't it?

**Comment by Peterkn2001** [comment]
Yes, you're right, apologies!

Pete.

**Comment by doom369** [comment]
@Peterkn2001 we improved the texts. Also, this table is planned to be refactored. So I think for now we are good here for now.
