### ISSUE TITLE
I am not able to login into the mobile app with the blynk.cloud credentials. Do I have to signup separately with the mobile app also? Why it is NOT working with the same profile information that I have created on the blynk web?

### ISSUE THREAD

**Issue by touhid360** [blynkkk/beta#111]

**Comment by doom369** [comment]
> Do I have to signup separately with the mobile app also?

No. Did you confirmed your account and was able to login into the app?

**Comment by touhid360** [comment]
> > Do I have to signup separately with the mobile app also?
> 
> No. Did you confirmed your account and was able to login into the app?

Yes, I have confirmed my account. I am able to log in to the web BUT when I tried to login into the mobile app, It's showing "User is not registered"

**Comment by doom369** [comment]
Looks like you're using hte wrong app. The new app called **Blynk IoT** - https://play.google.com/store/apps/details?id=cloud.blynk&hl=en_US&gl=US

**Comment by touhid360** [comment]
> Looks like you're using hte wrong app. The new app called **Blynk IoT** - https://play.google.com/store/apps/details?id=cloud.blynk&hl=en_US&gl=US

Superb. Thank Dmitriy. I was using the old app. Now its working perfectly.
