### ISSUE TITLE
Invalid Auth Token message

### ISSUE THREAD

**Issue by Ad758** [blynkkk/beta#114]
Hi, I'm looking for help with an "invalid auth token" message in the serial monitor after uploading an arduino sketch.

I've tried copying from the "device info" tab and also entering the auth code manually to avoid any problems with copy and paste, but haven't been able to add a new device.

I've gone through the documentation but haven't found a solution yet. 

Any help? Thanks!

**Comment by doom369** [comment]
Hi. Please provide us with the serial output

**Comment by Ad758** [comment]
[7425] Connected to WiFi
[7425] IP: 192.168.0.115
[7425] 
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ v1.0.0 on ESP8266

[7502] Connecting to blynk-cloud.com:80
[8202] Invalid auth token
[25501] Connecting to blynk-cloud.com:80
[26105] Invalid auth token

**Comment by doom369** [comment]
That's wrong server. Looks like you are connecting to the old server, not a
new one

**Comment by Ad758** [comment]
`  Blynk.begin(auth, ssid, pass);
  // You can also specify server:
  Blynk.begin(auth, ssid, pass, "blynk.cloud", 80);
  //Blynk.begin(auth, ssid, pass, IPAddress(192,168,1,100), 8080);
`
I've changed it to the new blynk.cloud server in the sketch, but still getting the "Connecting to blynk-cloud.com:80" and "Invalid auth token" message on serial.

Where else should I change it?

Thanks

**Comment by Ad758** [comment]
The "Blynk.begin(auth, ssid, pass, "blynk.cloud", 80);" line is not commented out on the sketch...

**Comment by Ad758** [comment]
This has been resolved - I needed to comment out the first "Blynk.begin" line.

Thanks for the help.

**Comment by doom369** [comment]
@Ad758 I"m glad, you find the reason!

**Comment by Ad758** [comment]
Thanks, been struggling with that since Friday!

 

Adrian Tromp

 

EarthSmart Technologies

Water, Ozone & Monitoring Systems

Ph: 082 449 5015 |  <http://www.earthsmart.co.za/> www.earthsmart.co.za

**Comment by Merlin-Arthur** [comment]
Please am having a problem upload my code to esp8266. any help?
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 1
cnt 

connected with DWIN, channel 2
dhcp client start...
ip:192.168.43.192,mask:255.255.255.0,gw:192.168.43.97
[10582] Connected to WiFi
[10582] IP: 192.168.43.192
[10582] 
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ v1.1.0 on ESP8266

 #StandWithUkraine    https://bit.ly/swua


[10712] Connecting to blynk.cloud:80
[11691] Invalid auth token
pm open,type:2 0

**Comment by hacksick** [comment]
> 

thank you so much it worked
