### ISSUE TITLE
Blynk.notify is not working

### ISSUE THREAD

**Issue by rmznsy** [blynkkk/beta#115]
Blynk.notify is not working. I saw that in the documantation [https://docs.blynk.io/en/web-dashboard/products/events](url). But it is not working for me. Is there a trick for it to work or just a bug?
Blynk Library 1.0.0
Nodemcu 1.0

**Comment by vshymanskyy** [comment]
You should use `Blynk.logEvent` instead of `Blynk.notify`:
https://docs.blynk.io/en/blynk.edgent/api/log-event

Sorry this is an error in the documentation. Working on a fix

**Comment by vshymanskyy** [comment]
Fixed, will appear soon in the docs. Thanks!

**Comment by doom369** [comment]
@rmznsy for the back-compatibility Blynk.notify still works. But notifications are sent only for the existing accounts. Anyway to avoid any problems in the future - please use `Blynk.logEvent` with notifications enabled.
