### ISSUE TITLE
Problem : Communication betwenn ARDUINO UNO, ESP32 and BLYNK

### ISSUE THREAD

**Issue by justine69** [blynkkk/beta#116]
Hi all,

I will need your help on a program that I am in the process of making.

I want to control an RGB LED strip (12V DC) and a fan (PWM) via the BLYNK application.

For this I have an Arduino UNO board and an ESP32.

I have the code for the Arduino UNO as well as for the ESP32 but I don't know which code to use to link the ESP32 to the Arduino.

Attached are the codes for the 2 cards.

Thank you in advance for your help
[sketch_arduino_uno.zip](https://github.com/blynkkk/blynk_Issues/files/6617490/sketch_arduino_uno.zip)

**Comment by blynkkk** [comment]
Hi, questions like that can be answered on our forum: http://community.blynk.cc . Please use search, and if there is no answer, please create a new topic. Thanks!
