### ISSUE TITLE
Radial Gauge is not working on Android App

### ISSUE THREAD

**Issue by rmznsy** [blynkkk/beta#117]
Radial Gauge is not working on Android App. 
Blynk IoT Android v1.1.2(32) 
Samsung S10e Android 11

It is just empty.
![Screenshot_20210608-195911_Blynk IoT](https://user-images.githubusercontent.com/81516108/121227826-af7f4280-c894-11eb-9db8-bfb0d01bf194.jpg)

**Comment by doom369** [comment]
@alexkipar could you pelase take a look?

**Comment by alexkipar** [comment]
We will soon release a new version with a fix to this issue

**Comment by doom369** [comment]
@alexkipar please close if fixed.

**Comment by rmznsy** [comment]
Still not working. Blynk IoT v1.1.3

**Comment by alexkipar** [comment]
@rmznsy, what do you have as min/max in your datastream used by this widget, and which values are you sending to it - same as in the datastream settings?

**Comment by rmznsy** [comment]
> @rmznsy, what do you have as min/max in your datastream used by this widget, and which values are you sending to it - same as in the datastream settings? 


I realized that it is working but value is not displayed.


![Screenshot_20210616-171441_Blynk IoT.jpg](https://user-images.githubusercontent.com/81516108/122235852-b296b600-cec6-11eb-9e21-726d44caf36f.jpg)![Screenshot_20210616-171430_Blynk IoT.jpg](https://user-images.githubusercontent.com/81516108/122235884-b7f40080-cec6-11eb-8c7e-b890a91225b5.jpg)

**Comment by alexkipar** [comment]
@rmznsy, thanks, got it; there is a check for the small size of the widget when we do not display its value. Also, there is an option in its setting not to display value.

**Comment by rmznsy** [comment]
@alexkipar okay. I see. After I make it bigger, it is showing the value.

**Comment by alexkipar** [comment]
@rmznsy cool, I will allow value for some smaller sizes in the next release; it seems it currently checks the wrong min size for the value enabled state.

**Comment by rmznsy** [comment]
@alexkipar yes, now I have to make it at least this big. ![Screenshot_20210617-192831_Blynk IoT.jpg](https://user-images.githubusercontent.com/81516108/122437408-5acd7d00-cfa2-11eb-8f95-4c9729befe52.jpg)
