### ISSUE TITLE
Feature request: Need bold numbers for Gauge and Labeled value widget

### ISSUE THREAD

**Issue by rmznsy** [blynkkk/beta#118]
Need bold font setting for Gauge widget, just like the old Blynk App. Under sun light or for older people who can not see very well, need bold numbers to see easily.

New App (Android 11, S10e, Blynk Iot v1.1.2):
![Screenshot_20210526-155912_Blynk IoT](https://user-images.githubusercontent.com/81516108/121232155-f58ad500-c899-11eb-815c-7ffe267ccd6d.jpg)

Old App (Android 11, S10e, Blynk 2.27.29):
![Screenshot_20210526-160009_Blynk](https://user-images.githubusercontent.com/81516108/121232173-fcb1e300-c899-11eb-837a-138271c0e395.jpg)

Also, for Labeled value widget, it is the same. It breaks the continuity in UI design. 

Labeled value widget, new App:
![Screenshot_20210608-203830_Blynk IoT (1)](https://user-images.githubusercontent.com/81516108/121232953-ca54b580-c89a-11eb-995b-cf5b62d9eeed.jpg)

**Comment by doom369** [comment]
> Labeled value widget, new App:

Yeah. This one should be fixed soon.

**Comment by alexkipar** [comment]
@rmznsy should be fixed in the latest version

**Comment by rmznsy** [comment]
Fixed, thanks.
