### ISSUE TITLE
Feature request: Entering Units Manually

### ISSUE THREAD

**Issue by rmznsy** [blynkkk/beta#119]
On new Blynk IoT App, Is it possible to change units manually? For example, I need to write "dk" instead of "min" (minutes) to Gauge. With old Blynk App, it was possible.

**Comment by doom369** [comment]
@rmznsy no. you have to set the main units that your hardware sends. Later Blynk will provide automatic conversion between supported types.

For example, your hardware sends celsius and your user wants to see kelvins. The user goes to settings, selects "kelvins" and blynk will automatically convert it.

**Comment by rmznsy** [comment]
Okay. I understand the point. So, maybe, there should be multi language support for the units in the future.

**Comment by doom369** [comment]
@rmznsy could you please provide an example, so I could better understand what do you mean?

**Comment by rmznsy** [comment]
@doom369 For example, my users speak Turkish, so instead of min (minutes), I want to show/write dk (dakika, minutes in Turkish) to the Gauge. It is not a big problem if it is not possible.

**Comment by doom369** [comment]
I see. That's another thing. It's actually a very big feature. We have it in plans, but it not gonna happen soon.
