### ISSUE TITLE
BLYNK.sync(V0) missing from library, Blynk.syncAll() working

### ISSUE THREAD

**Issue by spiutm** [blynkkk/beta#12]
i managed to sync the led value only with  Blynk.syncAll(); library doesn't recognize BLYNK.sync(V0)

error: 'class BlynkWifi<BlynkArduinoClientSecure<BearSSL::WiFiClientSecure> >' has no member named 'sync'
   Blynk.sync(V0);
         ^
exit status 1

**Comment by Peterkn2001** [comment]
The correct syntax is `Blynk.syncVirtual(V0)` and it's working fine for me.

Pete.

**Comment by spiutm** [comment]
> The correct syntax is `Blynk.syncVirtual(V0)` and it's working fine for me.
> 
> Pete.

nice
