### ISSUE TITLE
Terminal widget is not storing messages on Android App.

### ISSUE THREAD

**Issue by rmznsy** [blynkkk/beta#120]
Terminal widget is not storing messages on Android App. When you are in the app it shows the messages, however when you close and reopen it again, it shows blank.

I tried `Blynk.virtualWrite` and `terminal.print`.  Both did not fix it.

Blynk IoT v1.1.2(32)
Android 11, S10e

**Comment by doom369** [comment]
Not yet implemented.

**Comment by Luuciano27** [comment]
Tengo el mismo problema, el terminal no almacena los mensajes. Estoy usando un ESP32 DevKitC V4.
 Blynk Iot v.1.1.2 en android 10

**Comment by rmznsy** [comment]
@doom369 For my product, I use a terminal widget. When will it be implemented? I would be very happy if you prioritize this.

Thanks in advance.

**Comment by doom369** [comment]
@rmznsy it's in our roadmap. It' not hard to implement we just to do that in the most efficient way.

**Comment by Toro-Blanco** [comment]
@doom369 Any News on the progress of the terminal widget?

**Comment by doom369** [comment]
No work have been done here.

**Comment by italex33** [comment]
The thread was closed without being it solved, any update on this issue? I am using Blynk 2.0 which means I am paying for something better.

**Comment by Stynen** [comment]
Is it possible it is implemented now? My application (that I never changed hoping it might be fixed someday) now stores past messages sent to the terminal widget!

**Comment by doom369** [comment]
Yes. It was just recently fixed. For now only on Android. iOS and web comes next.

current limits - no history for free, 10 last messages for plus, 25 last messages for pro. We may change this is well and maybe we can make it configurable. We'll see.

**Comment by Stynen** [comment]
Super, thx!Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Dmytro Dumanskiy ***@***.***> Datum: 6/09/23  07:44  (GMT+01:00) Aan: blynkkk/blynk_Issues ***@***.***> Cc: Stynen ***@***.***>, Comment ***@***.***> Onderwerp: Re: [blynkkk/blynk_Issues] Terminal widget is not storing messages on Android App. (#120) 
Yes. It was just recently fixed. For now only on Android, iOS and web comes next.
