### ISSUE TITLE
Unable to invite user - You can't invite user with higher permissions than your current role

### ISSUE THREAD

**Issue by Aprngp** [blynkkk/beta#121]
I am trying to invite user from the Settings -> Users link but it gives me below error

You can't invite user with higher permissions than your current role

I am Admin and I am trying to add User role.

**Comment by doom369** [comment]
@Aprngp are you able to invite the admin?

**Comment by Aprngp** [comment]
Oh, yea, I was able to invite as Admin and the Edit the user to User

**Comment by doom369** [comment]
@Aprngp good, that's would be workaround until we fix the issue.

**Comment by doom369** [comment]
@Aprngp fix deployed.
