### ISSUE TITLE
Can not upgrade firmware over Blynk Air

### ISSUE THREAD

**Issue by OleksandrGora** [blynkkk/beta#122]
I have created a new shipment, chose the board, downloaded a new firmware in the shipment. By now: status - Live. Progress - none. There are more than 20 messages "Request sent" in Events history. Nothing happens. Should I modify my code to activate the feature?
![image](https://user-images.githubusercontent.com/85741797/121679877-8394d480-cac1-11eb-950c-d0e8d6d2981f.png)

**Comment by doom369** [comment]
@OleksandrGora do you have some serial console log from the hardware?

**Comment by OleksandrGora** [comment]
It is connected to network over WiFi. I use other library for ugrading the firmware over the air (can it be the reason?) I will connect it with usb, will let you know. Or (better) provide me please the code for sending some data to Blynk terminal on smartphone.

**Comment by doom369** [comment]
> I use other library for ugrading the firmware over the air (can it be the reason?) 

Yes. You need to use blynk firmware.

**Comment by OleksandrGora** [comment]
I mean there is a part of code with OTA firmware. While using Blynk air I do not use that firmware (I only mentioned it to say that usb connection is not used and I do not see serial console log). 

> need to use blynk firmware.

Should I insert a code in my program for using Blynk Air? As I understand I do not have to make additional programming for using Blynk Air. Connection main library should be enough. All magic happens there...

**Comment by doom369** [comment]
> As I understand I do not have to make additional programming for using Blynk Air. Connection main library should be enough. All magic happens there...

Yes. That's correct.

Looks like the device doesn't handle the firmware request. Only @vshymanskyy could help you here.

**Comment by OleksandrGora** [comment]
I noticed once such a message on serial console log:
dhcps: send_nak>>udp_sendto result 0

As addition: there is an external watchdog board. It is connected to RST pin of the ESP32 board (if it can help).

**Comment by doom369** [comment]
@OleksandrGora could you please post all serial output?

**Comment by OleksandrGora** [comment]
There is nothing after one hour waiting:
![image](https://user-images.githubusercontent.com/85741797/122111913-f20ec500-ce28-11eb-98b4-250b994fe946.png)
Log alerts before 9:20 PM was logged earlier then shipping was started.

**Comment by doom369** [comment]
@OleksandrGora please show the initial "connection" lines

**Comment by vshymanskyy** [comment]
You need to use Blynk.Edgent example.

**Comment by OleksandrGora** [comment]
After resetting the board:
![image](https://user-images.githubusercontent.com/85741797/122113971-6d717600-ce2b-11eb-8e00-94b5097a7d04.png)
Include list of used libraries: (can be interference between libraries?)
![image](https://user-images.githubusercontent.com/85741797/122114132-9c87e780-ce2b-11eb-9296-a4065148c089.png)

Blynk.Edgent did not used, you are right. Should I include some additional code for using Edgent? Is it not enough to use #include <BlynkSimpleEsp32.h>?

**Comment by vshymanskyy** [comment]
Please checkout examples in Arduino IDE: `File -> Examples -> Blynk -> Blynk.Edgent`
Those examples contain OTA implementation, which can be separated  easily and integrated in your sketch.
However I recommend integrating full Blynk.Edgent with Dynamic provisioning, etc.
