### ISSUE TITLE
Template doesn't show up in "add device"

### ISSUE THREAD

**Issue by davidmariag** [blynkkk/beta#123]
I added up to 3 templates and all works fine. On the forth template it doesn't show up in the drop down in devices. First tried login out and back in to see if it would refresh. I thought maybe the problem was no data streams enabled. Enabled a data stream and still it didn't appear in the drop down.

See pics...
![1](https://user-images.githubusercontent.com/61051937/121713382-7853a000-cae5-11eb-8865-e43ef917a6dd.PNG)
![2](https://user-images.githubusercontent.com/61051937/121713389-7a1d6380-cae5-11eb-836c-9c34aab0f5dd.PNG)

**Comment by doom369** [comment]
@davidmariag could you please refresh the page. Does that help? Do you see some errors in the web browser console?

**Comment by davidmariag** [comment]
Not in front of my system now. Please note I logged out and back in. Log in out and in would refresh it I think. I am using an older version of Chrome maybe that is the problem??

**Comment by doom369** [comment]
Logout may not help. As it could be an old script version loaded into a browser, so it's more effective to refresh the page.
I wasn't able to reproduce. Our Qa team will check as well.

**Comment by doom369** [comment]
@davidmariag fix deployed. Please reopen if reproduced.
