### ISSUE TITLE
Fatal error: BlynkEdgent.h: No such file or directory, Arduino, PlatformIO

### ISSUE THREAD

**Issue by deemoss** [blynkkk/beta#124]
<img width="971" alt="a" src="https://user-images.githubusercontent.com/2356886/121769226-0f167000-cb6b-11eb-8938-86c772d32b86.png">
Hi,

I am transitioning to Blynk 2.0. To start, I simply copied the Edgent example. PlatformIO and libraries are all lates versions. When I run it, I get “fatal error: BlynkEdgent.h: No such file or directory, Arduino, PlatformIO”. I have spent the last few hours troubleshooting this (also on blynk forums) with not much luck.

The only two libraries I use are Blynk and AccelStepper. Why do I get this error? It’s the same wether I use #include <BlynkEdgent.h> or #include “BlynkEdgent.h”.

`[env:az-delivery-devkit-v4]
platform = espressif32
board = az-delivery-devkit-v4
framework = arduino
lib_deps =
   waspinator/AccelStepper@^1.61
   blynkkk/Blynk@^1.0.0`

Cheers,
Dimos

**Comment by vshymanskyy** [comment]
You're using an incomplete example. Please use all files, i.e.: https://github.com/blynkkk/blynk-library/tree/master/examples/Blynk.Edgent/Edgent_ESP32

**Comment by vshymanskyy** [comment]
Please checkout examples in Arduino IDE: `File -> Examples -> Blynk -> Blynk.Edgent`
