### ISSUE TITLE
Superchart min max

### ISSUE THREAD

**Issue by kingstonheath** [blynkkk/beta#126]
In Superchart, min max values default to 0 and 100 an cannot be changed.

**Comment by kingstonheath** [comment]
Hi,
Thanks for the feedback.  Tried to change the min/max on one of my superchart data labels but no difference.  It lets me change the values but the values are not saved.  When I exit the datastream setting page and then go back into it again, values are back to 0 and 100.  I should say I am using android version 11

Steve

**Comment by kingstonheath** [comment]
I should also say I did dump the app cache and restart in case it was old settings being saved.

**Comment by alexkipar** [comment]
@kingstonheath which app version is this?

**Comment by kingstonheath** [comment]
Apologies.  App hadn't updated.  Tested and all is good.  Many thanks
