### ISSUE TITLE
Generate report gives no raw data

### ISSUE THREAD

**Issue by jbjbjb1** [blynkkk/beta#128]
In device dashboard, when I generated a report with raw data, it downloaded a zip file with a csv file, however the raw data csv file was blank. When I tried to re-generate the report it said there was not data available. When I tried again it gave me a zip file with a csv file, however the raw data csv file was again blank.

**Comment by doom369** [comment]
@jbjbjb1 do you have the datastreams with isRaw == true? Could you please attach generated file?

**Comment by jbjbjb1** [comment]
In my datasteam I only have the option for "Save raw data (plan restrictions apply)" which is false. In the help it says "By default server stores only 1 data point per data stream per minute." That level of raw data is fine for me. @doom369 is the setting somewhere else you mentioned?
[jb esp32 work phone_3100_data.zip](https://github.com/blynkkk/blynk_Issues/files/6646428/jb.esp32.work.phone_3100_data.zip)

**Comment by doom369** [comment]
> That level of raw data is fine for me.

If so you need to choose "minute" aggregation to get the data. "Raw" data is the data for the datastreams where "Save raw data" is true.
