### ISSUE TITLE
Unable to add new device 

### ISSUE THREAD

**Issue by kdharrigan** [blynkkk/beta#129]
I have an account with blynk however I'm confused about how the customer will add a new device in the app. I've created a template under my main account, and can add devices to my existing account. This process fails once I try adding a new device from a new blynk account to mimic the customer set up process. Any ideas will be greatly appreciated.
![failed provisioning](https://user-images.githubusercontent.com/57235227/121975587-f3b88a00-cd4f-11eb-9074-8c75e37731b2.png)

**Comment by doom369** [comment]
> from a new blynk account 

How did you make a new account? HAve you invited the user to the sub-organization?

**Comment by kdharrigan** [comment]
Hello Dmitriy,

Yes, I added a sub organization.

After attempting to log into the user to add a device I get the attached message.



Best regards,
Kevin Harrigan, Owner
Cell. 340-643-1573
www.yourideasvi.com
Your Ideas VI

**Comment by doom369** [comment]
Don't see any image.

**Comment by kdharrigan** [comment]
![errormsg 8946](https://user-images.githubusercontent.com/57235227/122058426-9bb66d80-cdb9-11eb-945d-efb81c272774.png)

**Comment by doom369** [comment]
@kdharrigan what role does your user have? Have you created mobile template?

**Comment by kdharrigan** [comment]
Dmitriy,

Configured as a user

Best regards,
Kevin Harrigan, Owner
Cell. 340-643-1573
www.yourideasvi.com
Your Ideas VI

**Comment by doom369** [comment]
I mean what role did you assign? Did you create a mobile template?

**Comment by kdharrigan** [comment]
Dmitriy,

I was able to resolve my problems. All were user error on my behalf.
1) There was a bit of confusion between my templates.
2) I did not make the proper assignments under the user roles.
    I had to allow the user role "user" to be able to add and provision devices.
