### ISSUE TITLE
Slider widget strange behaviour

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#13]
The "Show value" option on the Horizontal and Vertical Slider widgets doesn't work.

The Vertical Slider widget doesn't respond to the "knob" being moved, only tapping above or below the know will move the slider position.
The Horizontal Slider works correctly.

Pete.

**Comment by alexkipar** [comment]
@Peterkn2001 yep, we forgot to remove the 'show value' option - will be removed. You can always add value display widget on the same ds to show the value

I will check vertical slider work

**Comment by Peterkn2001** [comment]
> You can always add value display widget on the same ds to show the value

Have you actually tried that? I have and it doesn't work for me.

Pete.

**Comment by alexkipar** [comment]
@Peterkn2001 strange, it works on my side.
1. Set up the same data stream in slider and value/labeled display, 
2. Go back to device tiles
3. Open device - move slider and verify value in value/labeled display

**Comment by Peterkn2001** [comment]
Okay, The Value Widget wasn't displaying anything, but killing the app and re-launching it has fixed the problem.

Possibly related to issue #7

Pete.

**Comment by alexkipar** [comment]
@Peterkn2001 yep, it will be fixed with the next release.

**Comment by alexkipar** [comment]
@Peterkn2001 described issues should be fixed with just published 1.0.6, 'show value' switch is removed by now.

**Comment by Peterkn2001** [comment]
Tersting complete with version 1.0.6 of the app.

"Show value" option removed from H & V slider widgets.
Vertical slider control knob now responds as it should.

You can close this issue now - thanks.

Pete.
