### ISSUE TITLE
Suggestion:  Getting Started

### ISSUE THREAD

**Issue by Humancell** [blynkkk/beta#130]
This is some feedback from a new user of your platform.  I created my account, and my password, and got into the web console.  At that point I was just left in the "User Profile" with no direction on what to do next.

Yes, I've got the documentation open, but it also does not seem to have a "Getting Started" section.

Purely a suggestion for onboarding new users and customers, in both the web interface and documentation you might want to create some form of "Getting Started" guides.  In the web console maybe leveraging a one-time "tour" that would walk through what I am looking at, what the various nav pages are, and where my devices will eventually show up.  In the documentation the "Getting Started" guide might walk through the same ... now that I have a console account, what exactly do I do next.

Just a thought.  I'm now off to build a few devices and see if I can get them integrated into the platform.  All of your v2.0 stuff is looking great!

**Comment by Humancell** [comment]
BTW ... I did finally find this:  https://blynk.io/en/getting-started

But it was not linked from the Console (that I could see), nor the documentation.

**Comment by doom369** [comment]
@Humancell thanks for the feedback. We'll try to improve.

**Comment by blynkkk** [comment]
There is a link to documentation right from the console:
![image](https://user-images.githubusercontent.com/11541426/122118915-9deaed00-cdf6-11eb-8abd-33781d1ee550.png)

Also, there is a getting started guide.
![image](https://user-images.githubusercontent.com/11541426/122118987-b1965380-cdf6-11eb-8798-7af18ecb5b80.png)

![image](https://user-images.githubusercontent.com/11541426/122119018-ba872500-cdf6-11eb-96c0-1bb3bee616f8.png)


I understand that this could be improved, but in terms of links to documentation all works.
