### ISSUE TITLE
Unable to call BLYNK_READ

### ISSUE THREAD

**Issue by nbolton** [blynkkk/beta#131]
I'm unable to get this simple line to print to serial.

```
BLYNK_READ(V1)
{
  Serial.println("Test read V1");
}
```

I cannot see any Blynk widget settings that relate to frequency, and all examples appear to be for the legacy version of Blynk.

**Comment by doom369** [comment]
In Blynk 2.0 we removed `BLYNK_READ`

**Comment by nbolton** [comment]
Got it, timers only?

**Comment by doom369** [comment]
For now - yes. We haven't yet decided if we have to return this frequency reading. Usage in BLynk 1.0 is low and creates a high load on the server, however it good for the first-time experience. We'll wait for more feedback.

**Comment by nbolton** [comment]
The best feedback I can give you is: Please remove it from [the docs](https://docs.blynk.io/en/blynk.edgent/api/virtual-pins) and [help pages](http://help.blynk.cc/en/articles/512056-how-to-display-any-sensor-data-in-blynk-app) if has been removed from the code (or make it super clear in the docs/help that if you're using Blynk 2.0, which is likely, then it won't work).

**Comment by doom369** [comment]
Agree. Removed from the new doc.

**Comment by nbolton** [comment]
Impressive response time!
