### ISSUE TITLE
OnLine/OffLine Real Update

### ISSUE THREAD

**Issue by psnaherath** [blynkkk/beta#132]
Device OnLine/OffLine Real Updates option not work correctly. so can't find derive ofline or online and we can't conform Device operation working correctly. can you fix it like LED On Off real Time feedback system . 
Thank You

**Comment by doom369** [comment]
Could you please clarify how exactly it doesn't work? Did you setup any "OFFLINE IGNORE PERIOD" option in the template settings?

**Comment by psnaherath** [comment]
no im not set any Ofline ignored period. if i remove( power off) device but
web dashboard  indicate  still device is Online (Green). i checked Web page
reload, logout and relogin but it still online (green)

**Comment by doom369** [comment]
@psnaherath https://docs.blynk.io/en/blynk.edgent/mainoperations/devices-online-status

**Comment by psnaherath** [comment]
Hi friend..  It goes offline after few minutes like 10min but real time LED
feedback system is working correctly so There is a some problem on blunk
server.

**Comment by psnaherath** [comment]
Ok i will try it friend Thank you my friend
