### ISSUE TITLE
Dark Mode (with SuperChart)

### ISSUE THREAD

**Issue by svatos** [blynkkk/beta#133]
While in dark mode on phone, superchart with explicitly set white color of datastreems has black lines and also has a bold white font with shadows which makes it unreadable.

![IMG_20210617_165935](https://user-images.githubusercontent.com/10947341/122422630-96118100-cf8d-11eb-84e7-cec8a7bf2b84.jpg)
.

**Comment by blynkkk** [comment]
Dark theme wasn't implemented yet
