### ISSUE TITLE
Push notification for offline device

### ISSUE THREAD

**Issue by nbolton** [blynkkk/beta#135]
I notice that the notifications tab for the Offline event is not clickable. It would be useful to receive a push notification to my iOS device when the device goes offline.

Is this a planned feature?

**Comment by doom369** [comment]
@nbolton yes. would be implemented some day, but not on the priority list right now.

**Comment by nbolton** [comment]
Are you looking for contributors, volunteers, or businesses partners?

**Comment by blynkkk** [comment]
@nbolton thanks for asking! Could you please share your ideas on collaboration to iot@blynk.cc?

**Comment by vshymanskyy** [comment]
@nbolton currently you can enable Push notifications for offline events in your App Settings.
However it works for all devices (you cannot select devices).

This feature is on our roadmap.

**Comment by nbolton** [comment]
Excellent, found it.

![image](https://user-images.githubusercontent.com/313427/123136582-01a29500-d44b-11eb-9b2f-3f4011d46472.jpeg)

**Comment by nbolton** [comment]
I know this is closed, but I think offline notification for **specific** devices would be useful; I have a test device that I use for continuous integration testing, and every time the test runs, it causes my phone to tell me it went offline (a bit annoying).

So for now, I will disable the offline notification (but for someone who is not a developer, the "notify offline for all devices" feature is still useful in its current state).

**Comment by vshymanskyy** [comment]
Agree, we have an internal ticket for this (but no timeline yet).
