### ISSUE TITLE
SSID not showing up

### ISSUE THREAD

**Issue by Ad758** [blynkkk/beta#136]
I've used the Edgent_ESP32 example from the library, but I don't see the SSID showing up on the list of AP's on my phone or laptop to be able to add a new device.

Any help? Thanks

**Comment by vshymanskyy** [comment]
What is your arduino ide, esp32 core versions, board, hardware configuration, etc? 
Also, serial console output?

**Comment by Ad758** [comment]
Arduino ide is 1.8.15. 

ESP32 board is 2.0.0 alpha1

![image](https://user-images.githubusercontent.com/71893553/122665335-ec0d4100-d1a6-11eb-8f1f-883fa907e591.png)

Not sure how to get the esp32 core version - will send when I figure that out.

Boards used are ESP32 Wroom-32

![image](https://user-images.githubusercontent.com/71893553/122665590-65596380-d1a8-11eb-93a9-c37890054658.png)

![image](https://user-images.githubusercontent.com/71893553/122665546-24614f00-d1a8-11eb-9e06-9619e4cb0a70.png)

![image](https://user-images.githubusercontent.com/71893553/122665662-cd0fae80-d1a8-11eb-9080-3553f6d470e7.png)

Thanks!

**Comment by vshymanskyy** [comment]
So you have AP IP 0.0.0.0, probably due to some issue with the Beta ESP32
core. Please try the latest stable release of ESP32 sw, we will check the
beta in meantime.

**Comment by Ad758** [comment]
Thanks for the help, I changed the board to 1.0.6 and it's connecting.

![image](https://user-images.githubusercontent.com/71893553/122680514-cc4e3b00-d1ef-11eb-8e1e-59754963842d.png)
