### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#138]
At the bottom of this page:
https://docs.blynk.io/en/blynk.edgent/api/virtual-pins

there is a link to "changing widget properties". This is the URL for that link:

https://github.com/blynkkk/docs/tree/b7e1f17dc099ba9cebae3461a13ca2fe69b767a8/blynk.edgent/api/blynkfirmware.md#blynk-main-operations-change-widget-properties

but it gives a 404 error.

Pete.

**Comment by doom369** [comment]
@Mark-Pan please fix.

**Comment by Mark-Pan** [comment]
URL is changed to https://docs.blynk.io/en/blynk.edgent/mainoperations/widget-properties

**Comment by Peterkn2001** [comment]
Perfect, thanks.
