### ISSUE TITLE
Widgets display different values when "Device Tile" closed then re-opened

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#14]
I've set-up a simple app with three widhets...

A Button widget in Switch mode - range set to 0/1
A Horizontal Slider widget - range set to 0/255
An LED widget

The slider alters the brightness of the LED and the button turns the LED on and off.
The functionality of these widgets is working fine when the tile is open...

![image](https://user-images.githubusercontent.com/35718564/112727896-97965480-8f1c-11eb-8fac-7cbce8c9f6e3.png)

In this screenshot the slider is set to a value of 118 (according to my serial monitor, and widgets added to the web dashboard) and the button widget is Off, so the LED is not lit.

Closing this screen with the "X" in the top left takes me back to the device tile. Re-opening the device tile shows the widgets in this state:

![image](https://user-images.githubusercontent.com/35718564/112728007-0bd0f800-8f1d-11eb-82f5-b2762e3b77e9.png)

The button widget has gone from Off to On, and the slider has gone from 118 to 255. However, the LED widget still remains off.
The actual state of the virtual pins that the these widgets are connected to hasn't changed, that are still Off for the button and 118 for the slider, it's just the widgets that aren't reflecting this.

The web dashboard is still correct...

![image](https://user-images.githubusercontent.com/35718564/112728218-1c35a280-8f1e-11eb-9e37-20b13ee8819c.png)

Pete.

**Comment by alexkipar** [comment]
@Peterkn2001 is it still reproduces? if yes - can you send me logs from the next app's version (1.0.7) - it should be available in 30mins-1hour

**Comment by Peterkn2001** [comment]
It is still happening.
Here's a video made with version 1.0.6
https://www.youtube.com/watch?v=fkVNp3rDUj8

The Switch widget has a labelled value widget below it attached to the same datastream, and the slider widget also has a labelled value widget, which is above it and to the right.

The LED brightness is controlled by the slider, and the LEDE will be off if the switch is off.

You'll see that I turn the switch on, and set the slider to 255.
When I exit and re-enter, the labelled value widgets still show 1 and 255, and the LED is still on at full brightness, but the switch widget appears to be off, and the slider is no longer at the far right.

I'll upgrade to 1.0.7 when it's available and repeat then send the logs.

Pete.

**Comment by alexkipar** [comment]
@Peterkn2001 thanks, logs will be super useful, if possible - send them via email, it seems Github doesn't support file attachments.

**Comment by Peterkn2001** [comment]
Okay, I've upgraded to 1.0.7 and sent you the logs via email.

The problem still persists, and I think I understand it better now.
If I turn the button widget off and set the slider to 255 then kill the app and restart it, these are the values that it reverts to when the device tile is opened then closed again.

Pete.

**Comment by alexkipar** [comment]
New build 1.0.8 with a fix should be available soon

**Comment by Peterkn2001** [comment]
Confirm that this is fixed in 1.0.8

Issue can be closed - thanks.

Pete.
