### ISSUE TITLE
Slider widget on web dashboard sends value when browser focus is lost

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#140]
When a slider widget is used on the web dashboard then the widget sends is value to the Blynk server when the the user switches away from the web browser window to any other window (not necessarily a browser window).

This behaviour does not occur with with switch widgets.

Use the setup and code from issue #139 to demonstrate this issue.. When ever the web dashboard loses focus then the current slider value is sent to the server, causing the BLYNK_WRITE(V1) callback to trigger.

Whilst this behaviour isn't necessarily a problem. it could be could be problematic, if the slider were used to set a time delay for example, then that delay kept resetting each time the user switch to then away from the dashboard window.

Tested using Google Chrome Browser (Version 91.0.4472.114 (Official Build) (64-bit)) on Windows 10.

Pete.

**Comment by doom369** [comment]
Wow, nice catch. Thanks.

**Comment by Peterkn2001** [comment]
Ha! Only found it because of the syncAll testing, had me very confused for a while!

Pete.

**Comment by doom369** [comment]
@Peterkn2001 fixed. Please reopen if you see it again.
