### ISSUE TITLE
Extra data points for slope control

### ISSUE THREAD

**Issue by nbolton** [blynkkk/beta#142]
Feature suggestion: It'd be great if the slope control allowed for a custom number of data points (e.g. 4 data points) instead of only 2.

**Comment by nbolton** [comment]
Actually, perhaps I don't need more than 2 data points for what I'm doing. But, what would be a nice to have (visually) is if the line up to the 1st point started at 0,0 and the final line went to 100,100. Not very important because I can control how the points are used in code, but visually it would be good if it matched the behaviour of the code.

![image](https://user-images.githubusercontent.com/313427/123156779-9adca600-d461-11eb-80e3-ddcf67eff9a9.jpeg)

**Comment by blynkkk** [comment]
Unlikely to be implemented.
