### ISSUE TITLE
TTGO ESP32 Previous Program slowly fades in/out even when overwritten

### ISSUE THREAD

**Issue by jaymedavis** [blynkkk/beta#143]
I am using a LORA TTGO ESP32.  If I program it with a built in library of theirs (examples), I can program it and it works fine.  In my case I am using their meters example.  If I come behind that program and put blynk on the chip, so it only has BlynkEdgent.begin() in setup and BlynkEdgent.run() in loop(), it slowly fades in/out the meters display.  I'm not sure how this is happening, because I am essentially overwriting that program with an empty blynk program. 

None the less, if I take the meters program and add the two calls in setup() and loop() for blynk, it just slowly fades in/out the UI and makes any of my programming useless.

**Comment by vshymanskyy** [comment]
this is not a blynk issue.
your TFT screen just remembers the last picture it was showing. 

And blynk indicator is driving the screen backlight by coincidence. You should consult your module pinout

**Comment by jaymedavis** [comment]
alrighty.  my app works perfectly fine until I add blynk to it, then it causes it to fade in/out  🤷 

edit: not sure what the module pinout would help with?  I have nothing hooked up

**Comment by vshymanskyy** [comment]
Check out settings.h in your sketch
