### ISSUE TITLE
Can't share/transfer app dashboard to other users

### ISSUE THREAD

**Issue by Ad758** [blynkkk/beta#145]
Hi, I've created a new device and it's pulling data into the web dashboard no problem, but I can't share it with another user.

I plan to use the "Plus" version of the new Blynk until I'm comfortable to commit to the "Pro" version, so I don't want to create sub-organisations to do the sharing, as that feature is not offered with the Plus version.

When I do the transfer to the new user, they are sent the link by mail, but when logging in on the app they get told that the "dashboard is not available now" and that they don't have permissions to view the device:

![image](https://user-images.githubusercontent.com/71893553/123284601-aafd8f80-d50c-11eb-8730-2eddbca37777.png)
![image](https://user-images.githubusercontent.com/71893553/123284770-cd8fa880-d50c-11eb-8d2c-f1d2b958fcde.png)

I would think that the new Blynk is aimed at more commercial projects which would need to be shared easily with the developer's customers - is there an easier way to do this planned for the future?

**Comment by doom369** [comment]
@Ad758 hello. You need to invite that user to your org and only after the invite you can make the transfer.

**Comment by Ad758** [comment]
Thanks, they were invited and used the link in the mail, and the transfer was only done after they joined.
![image](https://user-images.githubusercontent.com/71893553/123292450-57427480-d513-11eb-80cd-e1f6f59356b5.png)
They got the mail to confirm that the device had been transferred to their account.

I uninstalled and reinstalled the app, same result.

**Comment by doom369** [comment]
@Ad758 please send me your email to dmitriy@blynk.cc I'll check.

**Comment by doom369** [comment]
solved in email (permissions were missing for the invited user)
