### ISSUE TITLE
Website improvement

### ISSUE THREAD

**Issue by srikumarc** [blynkkk/beta#146]
1. The Menu structure of the Website needs to be improved. Navigation to Templates and Devices is not very intuitive.
2. Data update is slow on widgets.

**Comment by doom369** [comment]
> Data update is slow on widgets.

Could you please provide more details?

**Comment by srikumarc** [comment]
Thanks Dimitry. I am new user of Blynk 2. I have a simple Nodemcu project
for water level monitoring using a ultrasonic sensor.

What I notice is that the web dashboard widgets such as chart and label
takes some time to update change in water level.

**Comment by doom369** [comment]
@srikumarc all Blynk dashboards updated in real time. If that's not true, most likely you have some issues with your hardware.

**Comment by doom369** [comment]
@srikumarc please reopen if you think there is some bug.
