### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by Ad758** [blynkkk/beta#147]
Is there a timer on the new app, to run a scheduled event every day?

I can't find anything in the documentation or in the app. Thanks.

**Comment by doom369** [comment]
@Ad758 hello., it was replaced with automations - https://docs.blynk.io/en/blynk.apps/automations

**Comment by Ad758** [comment]
Thanks but the Automations are not showing up on the customer’s mobile app, only on my app.

 

I want to turn on a relay at a set time each day, to run a circulation pump at a customer.

 

As a service provider I’d like to be able to provide that functionality in the app, but the customer must be able to change the circulation times as he wants, from his mobile app.

 

I hope we can do this with the new blynk app?

 

 

 

Adrian Tromp 

 

Ph: 082 449 5015

Water & Ozone Solutions

 <http://www.earthsmart.co.za/> www.earthsmart.co.za

**Comment by doom369** [comment]
> Thanks but the Automations are not showing up on the customer’s mobile app, only on my app.

How did you invite your customer?

> I hope we can do this with the new blynk app?

Yes. But it depends on the way you invited the customer.

**Comment by Ad758** [comment]
The device was transferred to them.

 



 

 

 

Adrian Tromp 

 

Ph: 082 449 5015

Water & Ozone Solutions

 <http://www.earthsmart.co.za/> www.earthsmart.co.za

**Comment by doom369** [comment]
@Ad758 automations are created per organization. So if you transferred the device to a sub-organization, you can switch to this sub-organization and create the automation there. The docs are missing right now. I'll update them.

**Comment by Ad758** [comment]
Thanks Dmitriy

 

I only have one organisation – Earthsmart technologies – there are no sub organisations.

 

 

 

Adrian Tromp 

 

Ph: 082 449 5015

Water & Ozone Solutions

 <http://www.earthsmart.co.za/> www.earthsmart.co.za

**Comment by doom369** [comment]
@Ad758 I see... In that case, that's about permissions like it was in the prev use case:

- Go to the **Settings** in the left menu
- Click on **Roles and Permissions**
- Click on **Organizations** and enable **Create/Edit/Delete/View Automations** permissions

**Comment by Ad758** [comment]
Great, thanks, I see it now.

 

Adrian Tromp 

 

Ph: 082 449 5015

Water & Ozone Solutions

 <http://www.earthsmart.co.za/> www.earthsmart.co.za

**Comment by Ad758** [comment]
Where do you set the conditions to send a notification?

 

I’ve checked permissions…

 



 

I don’t see anything like this:

 

https://docs.blynk.io/en/blynk.apps/automations

 



 

 

 

Adrian Tromp 

 

Ph: 082 449 5015

Water & Ozone Solutions

 <http://www.earthsmart.co.za/> www.earthsmart.co.za

**Comment by Ad758** [comment]
Ignore the last mail, think I found it in advanced settings…

 

Complicated way to set up a notification though.

 

Thanks

 

 

 

Adrian Tromp 

 

Ph: 082 449 5015

Water & Ozone Solutions

 <http://www.earthsmart.co.za/> www.earthsmart.co.za
