### ISSUE TITLE
Function Blynk.logEvent()  intermittent when I upgrade new firmware from midnight 25 Jun 2021. pls fix it

### ISSUE THREAD

**Issue by buihuuduc** [blynkkk/beta#148]

**Comment by doom369** [comment]
@buihuuduc hello, few more details would be helpful

**Comment by buihuuduc** [comment]
BLYNK_CONNECTED() 
{
  //sync TIME
  rtc.begin();
  blynk_connected = true;// update var blynk_connected
  gprs_connected = true;// update var gprs_connected
  Serial.println("[BLYNK] Blynk is connected");   
  Blynk.logEvent("mobile_connected", "Mobile is connected") ;
}
The line Blynk.logEvent() not working when I upgrade new firmware from 25/6/21 . Present I test 3 device for 1 template ID. Before it is working normal.
![event](https://user-images.githubusercontent.com/13497055/123508356-17a59500-d699-11eb-9e5b-c4204e1af552.png)
![event1](https://user-images.githubusercontent.com/13497055/123508357-18d6c200-d699-11eb-9efc-4e3ef624f7e3.png)
![event2](https://user-images.githubusercontent.com/13497055/123508401-681cf280-d699-11eb-8b19-bfc49752e859.png)

**Comment by buihuuduc** [comment]
I just test ESP32 use example Blynk 2.0 for interval every 10s send cmd Blynk.logEvent("interval_10s", "Send from ESP32 every 10S")  to server. But still not working and dissapear in infor item of timeline tab. Thanks all.

**Comment by doom369** [comment]
@buihuuduc we introduced recently some limits for the log events, as some users were sending too much:

- Only 1 event per second per event type is allowed
- You are limited to 100 events per device per day (without online/offline events)

For now, these limits could be removed only for white-label clients.

**Comment by buihuuduc** [comment]
> @buihuuduc we introduced recently some limits for the log events, as some users were sending too much:
> 
> * Only 1 event per second per event type is allowed
> * You are limited to 100 events per device per day (without online/offline events)
> 
> For now, these limits could be removed only for white-label clients.

**Comment by buihuuduc** [comment]
@doom369 thank you.
