### ISSUE TITLE
Is it possible to «Mark as resolved» an event on IOS app ?

### ISSUE THREAD

**Issue by ChristoTurmel** [blynkkk/beta#150]
Currently, i can't see where on my app to mark an event as resolved except going to the web dashboard. Is it normal ?
![image](https://user-images.githubusercontent.com/31734334/123523437-7bc45b00-d691-11eb-9a43-4393a24777e4.png)

Regards,
Christopher

**Comment by doom369** [comment]
@ChristoTurmel yes, you need to swipe the required event. left or right, don't rememeber.

**Comment by doom369** [comment]
@ChristoTurmel please reopen if it doesn't work.
