### ISSUE TITLE
Blynk.setProperty min/max attributes make no sense now datastreams have been introduced

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#151]
Previously, the min/max values of app widgets were set via the widget editing screen. This facility has now been removed, and these values are set in the datastream itself.

The `Blynk.setProperty(vPin, "max", value)` command still works, and is included in the documentation, but the way it works is confusing and the min/max attributes should probably be removed from this command.

Take an example of a slider widget attached to a datastream where the min/max range of the datastream is defined as 0-100.
When a `min` or `max` value is sent via `setproperty` it does alter the minimum and maximum values of the slider widget in the app (but not the web dashboard) and it allows a value outside of the allowable datastream values to be set. When the app slider is moved, the results are mimicked on an app widget in the web dashboard attached to the same datastream, until the app slider exceeds the maximum permissible value of the datastream. At this point the app slider shows the new value, but the web dashboard slider ignores the value because the value is outside the datastream minimum/maximum values.
This results in the app and web dashboard sliders being out of sync.

Putting the app into 'edit' mode then back into 'play' mode resets the min/max values to those of the datastream.

I'd suggest removing the min/max attributes from the `Blynk.setProperty` command, and possibly replacing them with the ability to programmatically set the min/max (and other) attributes of a datastream.

The documentation here would need updating too if this was changed....
https://docs.blynk.io/en/blynk.edgent/mainoperations/widget-properties

Pete.

**Comment by doom369** [comment]
Yeah, agree. Removed min/max from the doc description for now. Thanks!
