### ISSUE TITLE
Missing Witgets on IPhone6S when I upgrade to PLUS rev not available "PRO Witgets" pls fix

### ISSUE THREAD

**Issue by buihuuduc** [blynkkk/beta#155]

**Comment by buihuuduc** [comment]
I had upgrade to PLUS reversion but PRO widgets not available on IP6S. Refer to Blynk Price it have.

**Comment by doom369** [comment]
@buihuuduc hello. That's a bug, we already published the app update. Waiting for Apple to review it. Should be available in a day or two. Sorry for inconveniences.

**Comment by doom369** [comment]
@buihuuduc should be fixed with the new app update.
