### ISSUE TITLE
Upgrade flair still shows after subscribing

### ISSUE THREAD

**Issue by nbolton** [blynkkk/beta#157]
I paid for a subscription today, but I still see the icon/button flair for the upgrade call-to-action (this is why I upgraded, to get rid of these... and also to use the controls).

![image](https://user-images.githubusercontent.com/313427/123843871-42e2eb00-d90a-11eb-8871-f51617762089.png)

**Comment by doom369** [comment]
@nbolton we released the update with the fix yesterday. Waiting for the apple to review it. Sorry for the inconvenience.

**Comment by tuvalu22** [comment]
Seeing exactly the same on my IOS devices after paying 24 hours ago. Hope its ok put this here ?

**Comment by doom369** [comment]
@tuvalu22 hello. Did you check for the new app update? As far as I know the release is already available.

**Comment by doom369** [comment]
Unfortunately, the app update was rejected by Apple. We'll try to resubmit the app asap.

**Comment by tuvalu22** [comment]
Thanks Dumanskiy. Not a problem

Phil

**Comment by doom369** [comment]
@nbolton @tuvalu22 update is published. Please let me know if everything works as expected.

**Comment by tuvalu22** [comment]
Thanks Dmitriy updated and working ok
Phil

**Comment by nbolton** [comment]
Confirmed fixed here too 👍
