### ISSUE TITLE
My organization not accept for account user

### ISSUE THREAD

**Issue by buihuuduc** [blynkkk/beta#158]
Present I tested the functional of the **My organization** have to some problem as following:
1. Account user block login 
2. Account staff and admin had login but still not function Notify and email on Automation.
3. My just received notify and email from the **main organization**

**Comment by doom369** [comment]
> Account user block login

Could you please provide more details? Do you see some errors? Something else?

> Account staff and admin had login but still not function Notify and email on Automation.

Not yet implemented.

> My just received notify and email from the main organization

Please provide more details about your setup

**Comment by buihuuduc** [comment]
![login](https://user-images.githubusercontent.com/13497055/123928530-32894980-d9b8-11eb-839b-228591414529.jpg)
**case 1 as picture above**
**case 3** 
+ I config my **_Hierarchy is A company_** have two email duc@gmail.com and role Admin
+ _**Sub organization is B_company**_ have email dung@gmail.com role Admin, and 1 email thanh@gmail.com role Admin.
@ When I create project in **A company** and then transfer device to **B company**. At the B company i had  use automation function for device but i dont see notify and email send to dung@gmail, thanh@gmail, but the notify and email send to email duc@gmail of Hierarchy is **A company**.

**Comment by doom369** [comment]
> case 1 as picture above

Log in with your main account, go to settings, "Roles and permissions". Add desired permissions for the User role.

> case 3

At the moment automation sends emails/pushes to the creator/owner of the automation. We'll improve it and will add more options.

At the moment you may consider using Events instead of Automations.

**Comment by buihuuduc** [comment]
Thanks @doom369 . Unfortunately I had adjust User Role become to user of the main account **huuduc.electric@gmail.com**. It is account to pay money for Blynk. Present I can not do everything. Can you correct my account to role **Admin**.

**Comment by buihuuduc** [comment]
@doom369 My Receipt #2553-8754 and Paid June 29, 2021.  Thanks

**Comment by buihuuduc** [comment]
![image](https://user-images.githubusercontent.com/13497055/124051313-762a9480-da46-11eb-99f5-b4c2b9eb23f4.jpeg)
@doom369 Correct role to Admin as picture pls. 
+ In this case if the clients of Blynk had changed user role to user or staff of main account. The web app( Blynk.console) can retore the main account to the role Admin or the define it is role admin when the first register or contact with the Blynk.
Pls advise for this case to every Blynk's clients.

**Comment by doom369** [comment]
@buihuuduc changed.

**Comment by buihuuduc** [comment]
@doom369 Thanks.
