### ISSUE TITLE
Deleting a Device causes loss from Account

### ISSUE THREAD

**Issue by srikumarc** [blynkkk/beta#159]
I am currently using the free plan and had purchased an additional device on 29th May.  Due to some naming issues, I had to delete the device from the web application. When I tried  adding it again, I am being asked to pay for an additional device. Can you please correct the error? Deleting a device should not result in loss of already purchase credit which is supposed to be for lifetime.

**Comment by doom369** [comment]
@srikumarc hello. Thanks for the report. I'll check. Could you please provide your email? What does your billing section shows?

**Comment by srikumarc** [comment]
***@***.***

**Comment by doom369** [comment]
@srikumarc you can send me to email dmitriy@blynk.cc

**Comment by doom369** [comment]
@srikumarc I checked - looks like it's just a UI issue. Please refresh the page and it should allow you to add the device. We'll fix the UI issue in the meanwhile.

**Comment by srikumarc** [comment]
Unfortunately No, I refreshed the page and clicked on add a device but it
results in the same credit card payment pop up as below

[image: image.png]

**Comment by srikumarc** [comment]
I think your web page should have a provision to show  the membership type
"___" and total devices as "__"

**Comment by srikumarc** [comment]
The additional device that I had purchased is not restored yet.

**Comment by doom369** [comment]
@srikumarc we are preparing a deployment in order to fix your issue.

**Comment by srikumarc** [comment]
thanks
