### ISSUE TITLE
Adding tabs crashs the app

### ISSUE THREAD

**Issue by thomoray** [blynkkk/beta#16]
Phone Sony XZ2 Android 9
Tablet Samsung S6 lite Android 11

Add tabs to device
Exit developer mode and go back to device
When tapping on the device app exits

https://drive.google.com/file/d/1-ksrp6nuFAgQ7jrufhac-9jqiZ0vfHtg/view?usp=drivesdk

**Comment by alexkipar** [comment]
@thomoray thanks, we will soon publish a bugfix version with a fix to this issue too

**Comment by alexkipar** [comment]
@thomoray it is fixed in 1.0.6 build

**Comment by thomoray** [comment]
Confirmed all issues raised are now working.

**Comment by doom369** [comment]
Nice. @thomoray thanks for the confirmation
