### ISSUE TITLE
invalid auth token - static provisioning when connecting with IP address

### ISSUE THREAD

**Issue by kingstonheath** [blynkkk/beta#160]
In Blynk V1, I had problems after power failure with my system resolving the blynk-cloud.com address.  I started using the ip address to connect (Blynk.config(auth, "45.55.96.146", 8080);) and all was good.  When I converted to Blynk V2 (static provisioning), I cannot connect to the blynk.cloud server using the ip address - just keeps giving me an invalid auth token message in serial monitor.  Replacing the IP address with Blynk.config(auth, "blynk.cloud"); works most of the time but intermittently gives me the invalid token error on connection.  Is there a fix for this so I can return to using the IP address for connection?
I am in Australia
Thanks

**Comment by doom369** [comment]
@kingstonheath do you use the latest blynk firmware? Are you able to check the hardware serial console?

**Comment by kingstonheath** [comment]
Thanks for the response.  definitely using firmware V1.0.0 (no beta).  I just did a ping check to blynk.cloud and it returned a different ip address (64.225.16.22).  When I use this ip address, connects no problems.  Has the ip address for my region changed?

**Comment by doom369** [comment]
@kingstonheath **45.55.96.146** is Blynk legacy cloud. **blynk.cloud** is new cloud. Why do you expect **45.55.96.146**  to work with the new app/firmware?

**Comment by kingstonheath** [comment]
No reason why I expected 45.55.96.146 to work - just assumed it would and couldn't find any documentation to the contrary for the new firmware.  Certainly explains why I can't connect with it using the new firmware.  Should I use the ip address returned when I ping blynk.cloud (64.225.16.22)?
Thanks
Steve

**Comment by doom369** [comment]
> (64.225.16.22)

You can use it for testing. However, for reliability, it's better to use host `blynk.cloud`.

Thanks to your report I found a bug in our routing policy. During the ping, you should actually get the `128.199.144.129` (singpore), not `64.225.16.22` (new york). As you are in Australia... At the moment the simplest way to fix the routing would be to remove the account on blynk cloud and create it again (after new routing policies will be applied == ~2 hours from now). Is that possible for you? Or you already made a lot of setup or did a purchase?

**Comment by kingstonheath** [comment]
Thanks Dmitriy.  I have upgraded to the plus plan so don't know whether removing the account is an option.  I have 6 projects active on the new system so I would rather not have to rebuild them.
Steve

**Comment by doom369** [comment]
We can move the plan. But yeah, recreating the 6 projects is not a simple task. Ok, we'll leave it as it is for now. Maybe we'll have "transfer to region" functionality at some point

**Comment by kingstonheath** [comment]
Thanks.  So I use the NY address for testing? I suspect the dns resolving issue is with my ISP or my modem so would like to see if using it address resolves if.

Steve

**Comment by doom369** [comment]
> Thanks. So I use the NY address for testing?

Yes.
