### ISSUE TITLE
Super chart is crashing the Android Blynk IoT app

### ISSUE THREAD

**Issue by MagnusKihlbaum** [blynkkk/beta#161]
Added a super chart in the android app (v1.1.5 (36)) and the app is now crashing. Tried to clear app cache and data without luck

**Comment by doom369** [comment]
@alexkipar have you published the build with the fix already?

**Comment by alexkipar** [comment]
Bugfix will be available soon, possibly in 3-4 hours or later depending on Play store review duration

**Comment by alexkipar** [comment]
@MagnusKihlbaum, the new app's version should be already available

**Comment by MagnusKihlbaum** [comment]
Tested new version (1.1.6 (37)) and the SuperChart is no longer crashing the app. However it's not possible to add Datastreams to the Superchart

**Comment by alexkipar** [comment]
You should be able to add at least one datastream in free plan. Is the button disabled?

**Comment by MagnusKihlbaum** [comment]
Not possible to add any datastream to the Superchart. The Datastream section shows "+ Add Datastream" in green text . When 'clicked' nothing happens.

**Comment by alexkipar** [comment]
@MagnusKihlbaum yes, reproduced this state. We will upload a new version on Monday or Tuesday - it will contain a fix
