### ISSUE TITLE
 data not displaying

### ISSUE THREAD

**Issue by werpret** [blynkkk/beta#162]
Good day 
Have been working on my first new blynk project and all was working well and then suddenly some or most of my data is not displaying on my Ipone 6plus.

**Comment by doom369** [comment]
@werpret did you change anything on the firmware? Do you use the latest app version? Could you please send us the logs? It's hard to know what the problem is without more details.

**Comment by werpret** [comment]
Thanks I am at work now and will send it on later.

**Comment by werpret** [comment]
and yes i am using latest app version and did not change any firmware.

**Comment by doom369** [comment]
@werpret do yu have any updates?

**Comment by werpret** [comment]
I have the similar problem as #168  ,when I go into my template settings and select "erase all device data" and confirm "delete"
all goes back to normal. So I am not sure if its todo with the amount of data send to cloud, I am sending two ds18b20 at lowest resolution every 15 seconds and ADC value for water pump pressure every second and this works for about a day and then the same happens.
Thanks Werner

**Comment by doom369** [comment]
@werpret Could you please send us logs when you see "no data is displayed"?

**Comment by doom369** [comment]
@werpret do you still see the issue?
