### ISSUE TITLE
Widgets Blynk IoT

### ISSUE THREAD

**Issue by Tutnetdebilov** [blynkkk/beta#164]
Hello! There is no vidget "Time input" in the new app while everybody needs it. When can we expect it will be fixed? In the vidget "slider" I see no value in digits please fix it. In the vidget "SuperChart" the colour of the values in the left should be changed because now its the same as the diagram and you see nothing. Thank you! Kind regards! 
![Screenshot_20210701_230517](https://user-images.githubusercontent.com/86803462/124189349-da8a3a00-dac0-11eb-8d34-12dceb58d919.jpg)
![Screenshot_20210701_230352](https://user-images.githubusercontent.com/86803462/124189352-dbbb6700-dac0-11eb-8509-440eba32a751.jpg)
![Screenshot_20210701_230322](https://user-images.githubusercontent.com/86803462/124189354-dbbb6700-dac0-11eb-8cdc-b0eda206c2bf.jpg)

**Comment by doom369** [comment]
Hello.

> There is no vidget "Time input"

Yes. You can use automations instead - https://docs.blynk.io/en/blynk.apps/automations. They are not fully replacing the Time Input. But we gonna improve that.

> In the vidget "slider" I see no value in digits please fix it.

@blynkkk 

> In the vidget "SuperChart" the colour of the values in the left should be changed because now its the same as the diagram and you see nothing.

@alexkipar please take a look.

**Comment by Tutnetdebilov** [comment]
> Hello.
> 
> > There is no vidget "Time input"
> 
> Yes. You can use automations instead - https://docs.blynk.io/en/blynk.apps/automations. They are not fully replacing the Time Input. But we gonna improve that.
> 
> > In the vidget "slider" I see no value in digits please fix it.
> 
> @blynkkk
> 
> > In the vidget "SuperChart" the colour of the values in the left should be changed because now its the same as the diagram and you see nothing.
> 
> @alexkipar please take a look.

I need the timer to keep running if the device goes offline

**Comment by blynkkk** [comment]
>In the vidget "slider" I see no value in digits please fix it.

use the value label widget with the same datastream as slider and place it anywhere to show the slider value.

**Comment by Tutnetdebilov** [comment]
> > In the vidget "slider" I see no value in digits please fix it.
> 
> use the value label widget with the same datastream as slider and place it anywhere to show the slider value.

is it a temporary solution or will it remain so?

**Comment by alexkipar** [comment]
@Tutnetdebilov, it will remain; such implementation provides better options for configuration.

**Comment by Tutnetdebilov** [comment]
@alexkipar, while moving the slider - I don't know what value it is on ...
The old version of Blynk had a "show value" button and it was convenient. I will become more and more disappointed...

**Comment by alexkipar** [comment]
@Tutnetdebilov
1. Add additional value display or labeled display widget
2. Configure it with the same datastream
3. Set up it's UI options like font size, etc
4. Now moving the slider will show the value in that display widget with better UI than previous small text

**Comment by Tutnetdebilov** [comment]
@alexkipar, я извиняюсь, мне сложно на английском объяснить. Значения показывает только когда отпускаешь слайдер, а во время движения - не понятно на сколько переместил.

**Comment by alexkipar** [comment]
@Tutnetdebilov в настройках слайдера есть опция - отправлять значение сразу или же после того, как бегунок будет отпущен. Поменяйте эту настройку и получите желаемое поведение

**Comment by Tutnetdebilov** [comment]
@alexkipar но в таком случае на контроллер постоянно будут передаваться новые значения, a не только после того, как выставишь новое нужное значение и только тогда оно отправится на контроллер.
Мне не очень понятно зачем было вырезать всякие нужные функции, которые замечательно работали, а потом использовать какие-то костыли. Я заплатил за год Plus и до сих пор не могу полноценно использовать свое устройство потому что повырезали жизненно необходимые функции...

**Comment by blynkkk** [comment]
Было принято решение сделать более атомарный GUI. Ваше предложение мы услышали и подумаем что можно сделать. Правда в ближайшее время это изменение не будет сделано в связи с более приоритетными задачами. 

Если вам не подходит новая платформа, мы можем вернуть деньги. Напишите на iot@blynk.cc детали вашего аккаунта.

**Comment by Tutnetdebilov** [comment]
@blynkkk, спасибо за предложение. Почему бы просто дополнить существующий рабочий проект  новыми функциями, интерфейсом? Зачем вырезать? 
Я перешел на новую версию из-за веб интерфейса, что для меня было очень важно и интересно в дальнейшем.  Ну и новое оформление мне больше понравилось. 
Я посмотрел на ваши презентации и мне очень понравилась новая версия! 
Я планирую некое производство устройств, которые могли бы работать на вашей платформе. 
И я теперь должен искать другую платформу, только потому что вы решили повырезать какие-то функции? Это же бред. 
Вы действительно хорошая команда и сделали хороший продукт. Пожалуйста, примите во внимание просьбы пользователей, которым не хватает того, что было вырезано. Особенно это касается виджета "Time Input". Со всем другим я еще могу смирится... Простите, это мой крик о помощи просто.
