### ISSUE TITLE
Can't see multiple datastreams in one graph on cloud dashboard

### ISSUE THREAD

**Issue by PeterUrbanGreens** [blynkkk/beta#168]
It seems the cloud dashboard graph is only showing the first datastream that is selected in the dashboard template. This was working before but suddenly my grpahs have changed to only show datastream, while the others are still there in the template.

Moving another datstream to the top of the list in de template does also change the datastream in the actual dashboard.

**Comment by doom369** [comment]
> It seems the cloud dashboard graph is only showing the first datastream that is selected in the dashboard template.

Multiple datastreams per graph is now available only for paid plans.

**Comment by PeterUrbanGreens** [comment]
> Multiple datastreams per graph is now available only for paid plans.

But I do have a paid (Plus) plan. So why would this not work?

**Comment by doom369** [comment]
Could be a bug.
@alexkipar please advise.

**Comment by alexkipar** [comment]
@PeterUrbanGreens is this Android or ios. Which version?

**Comment by PeterUrbanGreens** [comment]
> cloud dashboard

@alexkipar, for now I am only using the web interface.

![actual dashboard](https://user-images.githubusercontent.com/86922065/124575851-6cdd6580-de54-11eb-91b3-65c3dd2293b2.PNG)
![dashboard config](https://user-images.githubusercontent.com/86922065/124575860-6ea72900-de54-11eb-88ea-539a42be9b35.PNG)

**Comment by doom369** [comment]
@PeterUrbanGreens do you have data for those DS? Please tell me your email I'll check.

**Comment by PeterUrbanGreens** [comment]
> @PeterUrbanGreens do you have data for those DS? Please tell me your email I'll check.

@doom369 I do have data. When I change the order of the datastreams in the template and put another one top, it shows the one on top. And when I generate a report I can see the values come through. And the data is used on tiles as well so pretty sure a klack of data is not the problem.

Nevertheless, my email is p

See tiles for the data coming through: 
![dashboard tiles](https://user-images.githubusercontent.com/86922065/124577488-f9d4ee80-de55-11eb-928e-9581dee94269.PNG)

**Comment by doom369** [comment]
@PeterUrbanGreens I think you're looking into the wrong dasbhoard. You need to open the device dashboard, not template dashboard. I see your data without any issues:

![screenshot-ny3 blynk cloud-2021 07 06-12_54_09](https://user-images.githubusercontent.com/1536494/124580957-4cfc7080-de59-11eb-9670-b2af70cbb854.png)


Also, please try to refresh the page + clean the cache. Does that help?

**Comment by PeterUrbanGreens** [comment]
> Also, please try to refresh the page + clean the cache. Does that help?

This seems to be the problem. It must have been from when my trial ended and took me a day to pay for a paid plan. When clearing cache (and web data) or opening in another browser or private window, it is indeed working.

Thanks for the assistance!
