### ISSUE TITLE
Blynk IOT - Location Widget on android will not save switch to satellite mode

### ISSUE THREAD

**Issue by wjcloudy** [blynkkk/beta#169]
Blynk IOT - Location Widget on android cannot switch to satellite mode. You can change the switch, but it always resets back to map mode.
Also (perhaps relation) the web dashboard map widget settings menu refuses to open.

**Comment by doom369** [comment]
> Location Widget on android cannot switch to satellite mode. You can change the switch, but it always resets back to map mode.

Android or ios?

> Also (perhaps relation) the web dashboard map widget settings menu refuses to open.

This one is fixed. Will be deployed soon.

**Comment by wjcloudy** [comment]
Thanks - Android

**Comment by alexkipar** [comment]
@jameswarner62 should be fixed in yesterday update

**Comment by doom369** [comment]
@alexkipar let's close by default and reopen if reproduced.

**Comment by wjcloudy** [comment]
Can confirm android map switch bug and the settings menu on web are both fixed - Thankyou!
