### ISSUE TITLE
Changing text size on Value and Labelled Value widgets has no effect

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#17]
Android device: Nexus 7 running Android 6.0.1
Blynk app version 1.0.6

Changing the text size settings in Value and Labelled Value widgets has no effect on the size or weight of the text.

Pete.

**Comment by alexkipar** [comment]
should be fixed in 1.0.7 version

**Comment by Peterkn2001** [comment]
Font re-sizing now works correctly in 1.0.7

This issue can be closed - thanks.

Pete.
