### ISSUE TITLE
No data to download when generating report

### ISSUE THREAD

**Issue by PeterUrbanGreens** [blynkkk/beta#170]
After my controller crashed I want to troubleshoot and download data from my now offline device. I'm logged in and can see the historic data in the graphs on my dashboard.

When I run a report for the last 24 hours on teh device page, trying to download raw data, the report generation starts, but it states there is no data. Yet there is clearly historic data in the graphs.

In the past I did do this succesfully, downloading all of the data streams. I'm not sure if teh device was online or offline at the time.

**Comment by doom369** [comment]
@PeterUrbanGreens maybe the data in the chart is aggregated data. Please try to download aggregated data from the report.

**Comment by PeterUrbanGreens** [comment]
Aah, yeah. That solves it. Thanks, sorry I did not try.

I assumed RAW data would be stored by default but just found the option on the datastream.

**Comment by doom369** [comment]
> I assumed RAW data would be stored by default 

It's not. In most cases 1 minute is enough, so that's why raw should be set explicitly. Also, this "raw" part will be restricted by plans.
