### ISSUE TITLE
Update particle library

### ISSUE THREAD

**Issue by blynkkk** [blynkkk/beta#172]
https://community.blynk.cc/t/particle-photon-showing-offline-using-new-blynk/54807/3

> after scanning through the library code, figured out that it looks at blynk.cloud if it finds #define BLYNK_TEMPLATE_ID in the code. I therefore rearranged the order so that is higher up [as below] and it now connects to blynk.cloud and shows online! 
```
#define BLYNK_PRINT Serial // Defines the object that is used for printing
#define BLYNK_DEBUG        // Optional, this enables more detailed prints
#define BLYNK_TEMPLATE_ID "myID"
#define BLYNK_DEVICE_NAME "myNAME"

// This #include statement was automatically added by the Particle IDE.
#include <blynk.h>
```

**Comment by vshymanskyy** [comment]
Library is on the latest version and behaves correctly
