### ISSUE TITLE
Roles and Permissions management absent from free plan

### ISSUE THREAD

**Issue by ChristoTurmel** [blynkkk/beta#173]
I am trying to find the option to change rules for the user group and staff group. As I can see on the plan-comparison webpage, there is no option to change that. The problem is my account still use my old settings when the pro plan was free. Is it normal that i can't change those settings with my free plan ?

Best regards,
Christopher

**Comment by doom369** [comment]
@ChristoTurmel hello. Yes. Permissions editing are not available under the Free plan. You can only use the default setup.

**Comment by ChristoTurmel** [comment]
Is it normal that the staff roll can only view organisation devices and user roll can only view Owners devices like i set when pro was free ?

**Comment by doom369** [comment]
If permissions were changed - that's correct.
