### ISSUE TITLE
Error parsing number message on Android

### ISSUE THREAD

**Issue by thorathome** [blynkkk/beta#175]
I am running on Win 10, iOS and on Android. (Android 11 on Google Pixel 3a XL)

I have 6 different devices, all on different templates. 

* When I add a widget - I have tried Value Display and LED - to one of my larger tiles on iOS, **it works as expected on iOS**, but causes an "Error parsing number" error message on Android when I try to open the tile. When I remove the new widget in iOS, the Android error message disappears. 
* The widget causing this behavior is connected to the last datastream on this device, number 15 . When I connect the new widget to a different datastream, I get no Android error message, iOS works as well. 
* The tile showing this behavior was created before the final datastream 15 was added in the template. I added the final datastream to the template, updated the device. When I added the new widgets to the tile, I saw the Android error.  

Hope this is helpful.

**Comment by doom369** [comment]
@thorathome could you please send the log right after you see the error it could speed up investigating?

**Comment by alexkipar** [comment]
@thorathome please send logs from Android apps About screen

**Comment by thorathome** [comment]
Sent.

**Comment by alexkipar** [comment]
@thorathome thanks!

**Comment by doom369** [comment]
@thorathome should be fixed now. You'll need to update the app. Please reopen if it's not fixed
