### ISSUE TITLE
Not seeing BLYNK_APP_CONNECTED and BLYNK_APP_DISCONNECTED on iOS and Android 

### ISSUE THREAD

**Issue by thorathome** [blynkkk/beta#177]
Hi Blynk. 

I am not seeing any calls to `BLYNK_APP_CONNECTED() `or `BLYNK_APP_DISCONNECTED()` using Android and iOS mobile apps. 
`BLYNK_CONNECTED()` works wonderfully, by the way.  

I rely on `BLYNK_APP_DIS/CONNECTED` primarily to initialize widget colors and labels, and have been using `BLYNK_APP_CONNECTED()` for years on old Blynk. 
Neither seems to be getting called now no matter what I do on the mobile iOS and Android apps. 

Hope this is helpful.

**Comment by doom369** [comment]
Hello. These handlers were removed as they were rarely used. You can implement your logic within `BLYNK_CONNECTED`, or you can use syncVirtual to fetch the state and decide whenever you want or not send somehting.

**Comment by Rabelbeat** [comment]
@doom369 BLYNK_APP_CONNECTED() / BLYNK_APP_DISCONNECTED() was very useful at my projects,
Examples:
1. My uncle is a farmer and he want to know what is the realtime of wind speed to know if to go out and spray the corn field,
so I develop a few solar power weather station with Particle Electron to him and implement
BLYNK_APP_CONNECTED() - if app connected update windspeed at realtime, app disconnected update server every 10 minutes.
BTW a few farmers interest to purchase this Solar Weather station, it very useful to them to know the status of wind speed if go out to spray the field or not ;)

2. Wifi car, implement failsafe by BLYNK_APP_DISCONNECTED()  - if app dissconnected > immediatley stoping car.

3. Wifi Drone,  if app dissconnected > immediatley land.

I'm preety sure there is more useful thing to implement with BLYNK_APP_CONNECTED() / BLYNK_APP_DISCONNECTED() .

It will be nice if you can return this handlers.

**Comment by doom369** [comment]
> app disconnected update server every 10 minutes.

Isn't that enough in your use case? I mean, when your uncle opens the app he sees the almost "fresh" value, so you don't need additional `BLYNK_APP_CONNECTED` logic here.

2, 3 seems very interesting. Thanks for sharing. I'll check if we can return it easily.
