### ISSUE TITLE
 fatal error: functional: No such file or directory

### ISSUE THREAD

**Issue by TejRajAdhikari97** [blynkkk/beta#178]
I have a problem when compiling projects with Blynk version 1.0.0. board Arduino UNO 
But when I use lower than version 1.0.0 i.e beta3 etc then this fatal error not showing and at that only show an ERROR of "no matching function for call to 'BlynkStream::begin(char [33], HardwareSerial&)'" and some program complies after using a lower version of blynk and some show no function matching as above. I don't know what's happening and what to do. I did much time uninstall and install blynk library.
while using the latest blynk version 1.0.0. then this shows;;
"from C:\Users\OnSite\Documents\Arduino\libraries\Blynk\src/BlynkApiArduino.h:14,
                 from C:\Users\OnSite\Documents\Arduino\libraries\Blynk\src/Adapters/BlynkSerial.h:18,
                 from C:\Users\OnSite\Documents\Arduino\libraries\Blynk\src/BlynkSimpleStream.h:18,
                 from C:\Users\OnSite\Documents\Arduino\final_smart_meter_tej1.0\final_smart_meter_tej1.0.ino:7:
C:\Users\OnSite\Documents\Arduino\libraries\Blynk\src/Blynk/BlynkConsole.h:20:10: fatal error: functional: No such file or directory
 #include <functional>
          ^~~~~~~~~~~~
compilation terminated."

 BlynkConsole.h at that path, the file exists but issue showing again n again
Need help to solve this problem

Arduino: 1.8.13 (Windows 7), Board: “Arduino Uno,

**Comment by doom369** [comment]
@TejRajAdhikari97 hello, you need to take the latest library version from the github - https://github.com/blynkkk/blynk_Issues/issues/106
