### ISSUE TITLE
Site profile, time zone, Moscow.

### ISSUE THREAD

**Issue by ilya7zz** [blynkkk/beta#179]
Error in the time zone for Moscow. Moscow uses UTC +3:00
<img width="501" alt="Снимок экрана 2021-07-10 в 20 49 47" src="https://user-images.githubusercontent.com/53345402/125172171-cdf09a80-e1c0-11eb-8c41-fa28f8520fe9.png">

**Comment by doom369** [comment]
@ilya7zz thanks for the report. It's just a UI issue. Shouldn't cause any troubles. We'll fix it anyway.

**Comment by doom369** [comment]
@ilya7zz should be fixed now. Please refresh the web browser to get the latest version.
