### ISSUE TITLE
no menus in app!

### ISSUE THREAD

**Issue by Philwzen** [blynkkk/beta#180]
logon to app, but no developermode icon, no icons execpt account related. web portal looks fine. cannot accesss anything from mobile app. tried both latest and legacy.  if it worked it would be very usefull but as it is no. is this a joke!!?

**Comment by doom369** [comment]
Hello. Did you switch to the sub-organization? Please check - https://docs.blynk.io/en/getting-started/developer-mode

**Comment by doom369** [comment]
@Philwzen please reopen if you can provide more info. right now it's not clear what the problem is.
