### ISSUE TITLE
Android app loading screen is strange

### ISSUE THREAD

**Issue by rmznsy** [blynkkk/beta#181]
There is an error in the loading image when you put the application in the background while on the device page and then enter the application again.

Blynk IoT App v1.1.8 
Galaxy S10e

![Screenshot_20210712-233401_Blynk IoT.jpg](https://user-images.githubusercontent.com/81516108/125353214-eb616800-e36a-11eb-81a4-40cd6f7b87e3.jpg)

**Comment by alexkipar** [comment]
The new app's version 1.1.9 contain a fix to this bug

**Comment by rmznsy** [comment]
Confirmed, thank you.
