### ISSUE TITLE
Android App. The information page is displayed instead of the timeline.

### ISSUE THREAD

**Issue by rmznsy** [blynkkk/beta#182]
When I click on a card from the notifications tab, the timeline tab is selected on the page that opens, but the information page is displayed.

Blynk IoT v1.1.8
Android App
Galaxy s10e

![Screenshot_20210713-123023_Blynk IoT (1)](https://user-images.githubusercontent.com/81516108/125429350-180b4dd1-2d04-4f42-9fe8-9a7bde95eb0f.jpg)

**Comment by alexkipar** [comment]
The new app's version 1.1.9 contain a fix to this bug

**Comment by rmznsy** [comment]
Confirmed, thank you.
