### ISSUE TITLE
 More than one device on the same mobile dashboard.

### ISSUE THREAD

**Issue by whogarden** [blynkkk/beta#185]
It's what I have done with the previous Blynk : version=0.6.1
Please follow that link :  https://1drv.ms/u/s!AumeH7O_5gYEquZX01DLlWEHStA5ZA?e=YjWHEe
In that Blynk project  there are 8 roller shutters driven by 4 ESP01.
On the same mobile dashboard, I have put 8 buttons to open them + 8 buttons to close them. 
![Blynk_Project2_PhoneNC](https://user-images.githubusercontent.com/16666934/125811580-30d3af7a-0760-41ad-bcc6-10fb44964607.jpg)

Can I do the same with the new Blynk 1.0?

**Comment by doom369** [comment]
@whogarden no. In blynk 2.0 you'll have 4 tiles with 2 led and buttons each.

**Comment by whogarden** [comment]
Suppose I am a roller shutter seller.
Each roller shutter is build with an ESP inside (in order to close or open it).
In the case where we need 8 roller shutters, I understand that we must have 8 tiles.
Is it correct?

I tried "ESP_NOW" with no success (I am not an expert).
Is ESP_NOW compatible with Blynk ino sketchs?
Thank you.

**Comment by doom369** [comment]
> In the case where we need 8 roller shutters, I understand that we must have 8 tiles.
> Is it correct?

Correct. You may find this to be a problem. However, you need to look into it from a business case perspective. You made 100 roller shutters. For 10 users you sold 1 item. For 20 users you sold 2 items. Etc. So every user will have a dynamic list that will be expanded automatically as a new device is added. With old project approach you couldn't make it.

However, I agree that for the "maker" use case it doesn't make much sense.

> Is ESP_NOW compatible with Blynk ino sketches?

It should, as far as I know.

**Comment by blynkkk** [comment]
Additionally, in [White-Label option](https://blynk.io/pricing ) we offer **grouping** of devices. Then, end-customers can create groups (bedroom windows, living room windows) and open/close shutters in a group with 1 button.

**Comment by whogarden** [comment]
Yes and it's very good
And what about the idea of a super tile where the user can gather widgets from different similar devices (a "bridge"?).

**Comment by whogarden** [comment]
I can see that ESP_NOW is not working.
It seems that it can't work when there is wifi already connected...
Am I right?
