### ISSUE TITLE
Change AP

### ISSUE THREAD

**Issue by Ad758** [blynkkk/beta#186]
Hi, if a device has been connected to a wifi router with Edgent, and the customer then wants to change their router, how is that done?

I don't see anything in the documentation.

Thanks

**Comment by doom369** [comment]
@Ad758 you can "reconfigure" the device. It should be somewhere in the device settings, in the device actions menu. Don't have my phone under my hand right now. But, yeah, the doc is missing

**Comment by Ad758** [comment]
Thanks, I did the reconfigure but I couldn't connect through Edgent after that (the device wasn't showing up to connect to). 

I deleted the device and then I could reconnect it. Not sure the "reconfigure" was working properly? Obviously don't want to have to delete all the device data if we need to change the router.

**Comment by vshymanskyy** [comment]
1. Hold the config reset button on the device for 10-15 seconds, release it. Device enters configuration mode.
2. In the App, navigate to your device and click `Reconfigure` in the menu. Follow the instructions.
3. Device should re-connect with the new credentials.

**Comment by doom369** [comment]
@vshymanskyy could you please add it to the documentation?

**Comment by Ad758** [comment]
Thanks, got it working using the "flash" button on the ESP8266, but on an ESP32, I still can't get the device to show up when reconfiguring.

**Comment by vshymanskyy** [comment]
It depends on your configuration of the firmware. Check out "Settings.h"

**Comment by Ad758** [comment]
Should I be assigning a button pin in settings.h? Not sure what I'm looking for...
![image](https://user-images.githubusercontent.com/71893553/126031828-700025dc-22e4-4497-9c77-c76fab08ad87.png)
Thanks

**Comment by vshymanskyy** [comment]
Correct. You may need to add some prints to verify this function.
