### ISSUE TITLE
On Web dashboard changing Label Widget's Level Color is not working 

### ISSUE THREAD

**Issue by rmznsy** [blynkkk/beta#19]
When you want to change the Level Color of Label Widget, it become grey.

Browser: Firefox 87.0 on Mac Os.

![Screen Shot 2021-03-28 at 15 30 48](https://user-images.githubusercontent.com/81516108/112752237-a7746e00-8fda-11eb-9ee8-9fb33473d020.png)

**Comment by Peterkn2001** [comment]
It's working okay for me, Windows 10, Chrome browser...

Changed from Blue to Orange...

![image](https://user-images.githubusercontent.com/35718564/112760528-2d021900-8fef-11eb-9b3b-a6055c9c3a6e.png)


![image](https://user-images.githubusercontent.com/35718564/112760539-3be8cb80-8fef-11eb-84ea-1a4a8809caf3.png)

Pete.

**Comment by doom369** [comment]
@rmznsy fix deployed.
