### ISSUE TITLE
ROLE Staff problem  change to admin

### ISSUE THREAD

**Issue by ghost** [blynkkk/beta#195]
Hi I have entered as a staff role, unfortunately I can no longer return to the admin role,
even if I enter admin again, a message is displayed indicating that the change in admin has occurred but in reality it doesn't change.

Message :
"Account data has been successfully updated"

![staff](https://user-images.githubusercontent.com/71384188/126655284-e5f808c7-fb09-407d-b1a0-32260b96f03b.png)

**Comment by doom369** [comment]
@Zanzaux please provide your email I can fix that manually. Could you please provide the steps? As we fixed that recently.

**Comment by Zanzaux** [comment]
my account is  peppe.insinga@hotmail.it

**Comment by doom369** [comment]
@Zanzaux fixed. Steps still would be nice to have.

**Comment by ghost** [comment]
Thanks, if you want I can try if it happens also by setting the invitation user role of the screenshots of each step.

**Comment by ghost** [comment]
User role setting is not done, here are the steps taken.
![1](https://user-images.githubusercontent.com/71384188/126668749-1a94df00-e4ef-4e37-b261-9cbf14c6c499.png)
![2](https://user-images.githubusercontent.com/71384188/126668761-8724cb33-71f5-4955-b238-6a0b054b6d04.png)
![3](https://user-images.githubusercontent.com/71384188/126668770-2f8d2e1e-6c18-40f9-ba4e-b8948ef7acfd.png)

**Comment by ghost** [comment]
Even setting staff again, the role is not changed and remains "admin"

**Comment by ghost** [comment]
I managed to change the role from "settings" unfortunately I can't go back to admin ...

![new1](https://user-images.githubusercontent.com/71384188/126669809-a83ad229-d190-4811-8b19-4d8f52b0e83c.png)
![new2](https://user-images.githubusercontent.com/71384188/126670177-f0a7aa29-f6bf-49d4-99d8-74abab2c0b59.png)

**Comment by doom369** [comment]
@Zanzaux you need to refresh the browser cache. This issue was fixed. The field is disabled:

![screenshot-fra blynk-qa com-2021 07 22-18_56_49](https://user-images.githubusercontent.com/1536494/126670163-94e5d84d-10a2-4ff3-acdc-03143d817069.png)

**Comment by doom369** [comment]
@Zanzaux returned admin role one more time.

**Comment by Zanzaux** [comment]
Unfortunately I was stuck in the staff, I also deleted the cache but nothing to do ...

![staff](https://user-images.githubusercontent.com/71384188/126671909-f2e430d3-5a89-4025-9a8f-fda7bfa49afa.png)

**Comment by ghost** [comment]
Unfortunately I was stuck in the staff, I also deleted the cache but nothing to do ...
![staff](https://user-images.githubusercontent.com/71384188/126672146-38f2eab1-5d3e-47ff-b4ca-82d543f8edd2.png)

**Comment by doom369** [comment]
I changed it. Or you have another acc?
