### ISSUE TITLE
Web Dashboard Switch Widget not working

### ISSUE THREAD

**Issue by ExcitePrime** [blynkkk/beta#197]
hello, the switch widget in the web dashboard is kind of stuck, even though i had deleted the widget and made a new one

![image](https://user-images.githubusercontent.com/61999025/127259466-541180c8-eb9c-478d-aa78-4204d2ed1178.png)

**Comment by ExcitePrime** [comment]
this happens when the widget is connected to virtual pin v0 by the way, and when i try to use other virtual pins, the widget works fine

the web dashboard switch also wont actuate when i turn on the button switch which has the same V0 datastream on the mobile dashboard

**Comment by doom369** [comment]
@ExcitePrime fix is deployed. Please reopen if the bug still occurs.
