### ISSUE TITLE
WiFi Connection

### ISSUE THREAD

**Issue by Ad758** [blynkkk/beta#198]
Hi, when connecting with Blynk.Inject I get a "Connection with device was interrupted" error?

I've used the same network credentials before with no problems.

![image](https://user-images.githubusercontent.com/71893553/127325717-944c4bd9-50fe-44cd-a205-700d888580a5.png)

**Comment by doom369** [comment]
@Ad758 hello, android, ios? Have you send the logs?

**Comment by doom369** [comment]
@Ad758 please reopen if you have more info.
