### ISSUE TITLE
I need a "push button" automation

### ISSUE THREAD

**Issue by whogarden** [blynkkk/beta#201]
In my project, I use some push buttons, but how can I use automation to : 
1 . set the push button to "On" 
2 . then after one second or two, the push button should automatically be set to  "Off".
We should appreciate a kind of momentary automation.

**Comment by doom369** [comment]
>  set the push button to "On"

What should trigger that event?

**Comment by whogarden** [comment]
I just want to momentarily activate a relay like when you briefly press the button on a remote control to command the opening or closing of a garage door.

**Comment by blynkkk** [comment]
Hello, now you can use "Wait" feature of Automation

**Comment by whogarden** [comment]
Tests in progress...

**Comment by whogarden** [comment]
Really very good.
Thank you.
