### ISSUE TITLE
Problem Transferring device to customer

### ISSUE THREAD

**Issue by kdharrigan** [blynkkk/beta#202]
I'm unable to add my device from the customer app even after sending them an invite. I can add from my main account but when i try to transfer to the customer, the transfer process is successful but the customer app is empty with no device. this problem seems to be specific to the customer email address as i cannot replicate it with another account.

**Comment by kdharrigan** [comment]
![Screenshot 2021-08-07 at 5 12 17 PM](https://user-images.githubusercontent.com/57235227/128614071-4903391b-c26b-4fcb-a90b-ecacdf233e34.png)


Here is what the customer account looks like after transferring the device to them. this is on a IOS device.

**Comment by doom369** [comment]
@kdharrigan customer should be within your organization or your suborganization. Is that the case? Otherwise you can't share the device with him.

**Comment by kdharrigan** [comment]
@doom369 customer is in my organization and sub organization.

**Comment by doom369** [comment]
@kdharrigan please provide email of the customer that doesn't see the device.

**Comment by kdharrigan** [comment]
@doom369 this is happening across a few email addresses. 
1) loubieparis@gmail.com
2) ljpropman@gmail.com

**Comment by kdharrigan** [comment]
I've now noticed that i can no longer provision devices in my sub organization. I will check my Roles and permissions.

**Comment by doom369** [comment]
@kdharrigan hm... all seems correct. Are you able to send the logs from the above account?

**Comment by kdharrigan** [comment]
Sure.

**Comment by doom369** [comment]
@kdharrigan please let me know when done. (you can send it directly to me dmitriy@blynk.cc)

**Comment by kdharrigan** [comment]
@doom369 . Sent

**Comment by doom369** [comment]
@kdharrigan Thanks. I think I found the root cause. So in order to fix the issue, you need to:

- Create a new Organization
- Transfer the user to the newly created org
- Transfer the devices to this new org
- Remove the old org

This should fix the issue. Please do not make the user as "developer". We'll disable this thing to avoid such problems in future.

**Comment by kdharrigan** [comment]
Dymitriy,

How do you make the user as a “developer”? I do not see this option. 

Best regards,
Kevin Harrigan, Owner
Cell. 340-643-1573
www.yourideasvi.com
Your Ideas VI

**Comment by doom369** [comment]
@kdharrigan please ignore my comment about "developer". You need to follow the above steps in order to fix the issue. Let me know how it goes.

**Comment by doom369** [comment]
@kdharrigan please reopen if above instructions didn't help.

**Comment by kdharrigan** [comment]
creating a new organization worked. I'm trying to figure out how it happened. I transferred a few devices to the new org  and it worked perfectly. Thank you for assisting. @doom369

**Comment by doom369** [comment]
@kdharrigan it happened due to a bug on the server side. the bug is fixed and now you should not see this behavior.
