### ISSUE TITLE
automation issue

### ISSUE THREAD

**Issue by Pekik1266** [blynkkk/beta#206]
I am using automation feature to monitor controlled room temperature, which was set on 31 degrees C to trigger a notification send to all phone cell.
first and biggest issue is that its trigger not in the correct temperature setting (which is 31 C), its randomly trigger on 29 or sometime in 30 C, the temperature chart is not show any spike or temperature rise to trigger the notification

**Comment by doom369** [comment]
@Pekik1266 the value could be changed right after the trigger, so you may think it's not a valid, but it is. Do you store the "raw" data? As by default graph shows "average per minute", not max or every data point.

**Comment by Pekik1266** [comment]
Thank you for your reply, I will check on raw data.At the moment I dont need to be that precise on the triger point, the average value as triger point is more than enough. Can automation feature use that value as triger point?Thanks and regardsPekik
-------- Original message --------From: Dmitriy Dumanskiy ***@***.***> Date: 8/14/21  20:58  (GMT+07:00) To: blynkkk/blynk_Issues ***@***.***> Cc: Pekik1266 ***@***.***>, Mention ***@***.***> Subject: Re: [blynkkk/blynk_Issues] automation issue (#206) 
@Pekik1266 the value could be changed right after the trigger, so you may think it's not a valid, but it is. Do you store the "raw" data? As by default graph shows "average per minute", not max or every data point.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/blynkkk/blynk_Issues/issues/206#issuecomment-898897977",
"url": "https://github.com/blynkkk/blynk_Issues/issues/206#issuecomment-898897977",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
