### ISSUE TITLE
error compiling Edgent ESP32 for MKR1010

### ISSUE THREAD

**Issue by wiwins01** [blynkkk/beta#208]
Followed setup instructions for new account, but unable to compile Edgent ESP32 on my MKR1010.  Arduino 1.8.12/Mac 10.13.6.  "Uncomment your board, or configure a custom board in Settings."; is there a #define for the MKR1010 board?

**Comment by vshymanskyy** [comment]
For MKR1010, there is a separate Edgent example in the library.
