### ISSUE TITLE
Menu widget issues

### ISSUE THREAD

**Issue by Bresca-eng** [blynkkk/beta#209]
Blynk library version: [1.0.1]
IDE: [Arduino]
IDE version: [1.8.15]
Board type: [MKR1010]
Additional modules: [...]
Blynk app: [3.2.4(1)]
OS: [iOS 14.7.1]

### Scenario, steps to reproduce
I'm experimenting problems with menu widget: I would like to add some items in menu but it is not possible or, better, initially I have correct menu then (after 1-2 minutes) it disappears
I have a template  called TestMenu with an only widget: menu widget. 
![Istantanea schermo 2021-08-18 (09 43 44)](https://user-images.githubusercontent.com/89138355/129894658-a92da44b-de3f-4686-9e38-120308250044.png)

It is linked to a virtual pin V0 in following way
 
![image](https://user-images.githubusercontent.com/89138355/129894825-61f2e321-a6db-487c-8a2c-6a04f5d953ae.png)

Software comes from Blink.Edgent example of Blynk library and is so-made

~~~
// Fill-in information from your Blynk Template here
#define BLYNK_TEMPLATE_ID "TMPLwuxyywbi"
#define BLYNK_DEVICE_NAME "TestMenu"
#define BLYNK_FIRMWARE_VERSION        "0.1.0"
#define BLYNK_PRINT Serial
//#define BLYNK_DEBUG
#define APP_DEBUG
#include "BlynkEdgent.h"

String MenuItem[10]={"S0","S1","S2","S3","S4","S5","S6","S7","S8","S9"};

BLYNK_CONNECTED()
  {
  BlynkParamAllocated items(128);
  for (int i=0;i<10;i++) items.add(MenuItem[i]);
  Blynk.setProperty(V0, "labels", items);
  SerialUSB.println("Menu' updated!");    
  }

void setup()
  {
  Serial.begin(9600);
  delay(2000);
  BlynkEdgent.begin();
  }

void loop() 
  {
  BlynkEdgent.run();
  }
~~~

### Expected Result
I expect to obtain...
![Istantanea schermo 2021-08-18 (13 02 14)](https://user-images.githubusercontent.com/89138355/129895598-0bbc8d5d-6bac-41c5-ac2c-d25527193087.png)

### Actual Result
Actually I get the screen seen before with the 10 items, but if I lock the phone and after 1-2 minutes I go back to see the screen, I find ...
![Istantanea schermo 2021-08-18 (13 04 03)](https://user-images.githubusercontent.com/89138355/129895985-6bd04def-8e0d-473a-afbd-3bf1e2ebf006.png)

You can see also this discussion on Blynk forum: https://community.blynk.cc/t/menu-widgets-issues-on-blynk-2-0/55700/3

Bresca-eng

**Comment by doom369** [comment]
@eepetrash please take a look

**Comment by eepetrash** [comment]
>   Blynk.setProperty(V0, "labels", items);

> if I lock the phone and after 1-2 minutes I go back to see the screen

@doom369 looks like server did not update `labels` property

**Comment by Bresca-eng** [comment]
If it can be useful, I got the similar behavior with an android phone.

**Comment by doom369** [comment]
@Bresca-eng bug confirmed. We'll fix it soon.

**Comment by doom369** [comment]
@Bresca-eng fixed. Please reopen if not.

**Comment by Bresca-eng** [comment]
It seems to work. Thanks!
