### ISSUE TITLE
Superchart issues

### ISSUE THREAD

**Issue by thomoray** [blynkkk/beta#21]
Tablet Samsung s6 lite Android 11

Adding a super chart to the device has the following issues

* add datastream does not save unless y-axis type is changed
* chart does not display data unless app restarted

https://drive.google.com/file/d/107wZukg0DCrnPGxXYc1nTme-h64FCysm/view?usp=drivesdk

Cheers

Ray

**Comment by alexkipar** [comment]
@thomoray app restart issue should be fixed in the latest build, which version are you using?

**Comment by alexkipar** [comment]
should be fixed in 1.0.7 version

**Comment by thomoray** [comment]
@alexkipar confirmed everything is now working.

Cheers
Ray
