### ISSUE TITLE
Bridge widget missing on new Blynk

### ISSUE THREAD

**Issue by ptasson** [blynkkk/beta#210]
I am working on a project that requires 12 esp8266 to work together to manage 12 gas fired furnaces. the new Blynk App. does not have the "bridge" widget. Is there any other way to accomplish this on the newer Blynk? Thanks.

**Comment by doom369** [comment]
@ptasson hello. you can look into automations. It may fit your needs - https://docs.blynk.io/en/blynk.apps/automations
