### ISSUE TITLE
Web Dashboard not reading virtual pins

### ISSUE THREAD

**Issue by mtkreitz** [blynkkk/beta#211]
ESP32 using DHT11 and capacitive moisture sensor, connected over WiFi SSL.

1. App on iOS reports values from virtual pins correctly
2. Serial monitor reports them correctly
3. Web dashboard (Label) widget **DOES NOT** report them correctly.

#define BLYNK_FIRMWARE_VERSION        "0.1.0"
#define BLYNK_PRINT Serial
#define BLYNK_TEMPLATE_ID "XXXXXXXXXXXXXXXXXXXXXXXXX"
#define BLYNK_DEVICE_NAME "SoilSensor01"

#define DHTTYPE DHT11
#define DHTPIN 22
#define SOILPIN 32

#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <BlynkSimpleEsp32_SSL.h>
#include "DHT.h"

DHT dht(DHTPIN, DHTTYPE);

BlynkTimer timer;

char auth[] = "XXXXXXXXXXXXXXXXXXXXXXXX";
char ssid[] = "XXXXXXXXXXXXXXXXXXXXXXXX";
char pass[] = "XXXXXXXXXXXXXXXXXXXXXXXX";

void setup()
{
  // Debug console
  Serial.begin(115200);
  Blynk.begin(auth, ssid, pass);
  dht.begin();
  timer.setInterval(5000L, sendSensor);
}

void loop()
{
  Blynk.run();
  timer.run();
}

void sendSensor()
{
  int humidity = dht.readHumidity();
  int temp = dht.readTemperature(true); 
  int moisture = analogRead(SOILPIN);

  Blynk.virtualWrite(V5, humidity);
  Blynk.virtualWrite(V6, temp);
  Blynk.virtualWrite(V7, moisture);

  Serial.print ("Humidity: ");
  Serial.println (humidity);
  Serial.print ("Temperature: ");
  Serial.println (temp);
  Serial.print ("Soil Moisture: ");
  Serial.println (moisture);
}

**Comment by doom369** [comment]
> Web dashboard (Label) widget DOES NOT report them correctly.

What do you mean by that? Do you have example?

**Comment by mtkreitz** [comment]
Sure, attached are (4) files.

First is the iOS app on my phone, showing the correct values
Second is the serial monitor from Arduino, showing the correct values via Serial.Print.
Third is the datastream configuration for just humidity
Fourth is the Web Dashboard showing incorrect value.

Thank you.
![iOS_App](https://user-images.githubusercontent.com/25873071/130066317-30bb3d2a-a8e9-4c90-882b-867309c95cae.jpg)
![Terminal](https://user-images.githubusercontent.com/25873071/130066582-cac91d14-a123-4963-8694-0062e8a55b3f.jpg)
![vPin_Datastream](https://user-images.githubusercontent.com/25873071/130066323-845e44d2-356d-41e7-b78b-b913d01e2305.jpg)
![Web Dashboard](https://user-images.githubusercontent.com/25873071/130066327-507a9a20-3f68-4fd6-a419-4ec6e4054f9a.jpg)

**Comment by doom369** [comment]
@mtkreitz thanks. that's a template dashboard, not device dashboard. It's shows fake data as this is a template it just shows you how the data will look like on the real device. In order to see the real data open the search view and click on "My devices".

**Comment by mtkreitz** [comment]
Thank you!
