### ISSUE TITLE
Analog pins on arduino mega

### ISSUE THREAD

**Issue by semy821** [blynkkk/beta#212]
Hello, i start using Blynk iot and i have an arduino mega, but when i create a Datastream i am limitetd on 4 analog pins. 
How do i change something to get all analog pins?

**Comment by EarlOld** [comment]
@semy821 Hi. Yep, we have this limitation for now. You can use virtual Datastreams. Link to docs: https://docs.blynk.io/en/blynk.edgent/mainoperations/virtual-pins
