### ISSUE TITLE
Any doc for Blynk Iot Time Input widget

### ISSUE THREAD

**Issue by thorathome** [blynkkk/beta#216]
Thanks for including the Time Input widget in Blynk IoT. 
I used them extensively in Old Blynk for input and display. 

**Looking for any doc on the Blynk IoT Time Input widget.** 
- How to set up the Datastream, for example.

Got any examples or doc on the new Time Input widgets? 
Thanks.

**Comment by doom369** [comment]
It works in the same way as before. The only difference you need to create the Data Stream on Blynk.Console (web portal) with the type **String**
