### ISSUE TITLE
Numeric input widget sending values before the number is completely entered.

### ISSUE THREAD

**Issue by Selah50** [blynkkk/beta#219]
Hi.  I am using the numeric input widget with my project.  When I tap on the widget to directly enter in a value, as I am typing in my value, it is being sent to my device in real time.  For example, if I tap on the widget and bring up the keyboard, enter 1, it immediately sends the value 1 to my device before I tap the send button.  It will send any value, even if it is outside of the min/max that I defined for the datastream.  This is very problematic for my device because I never want a value below what I defined for my datastream to be sent.  I will provide a link with a video to show what I am talking about.  I am using an esp32 based device, and running android 12 with the latest version of the Blynk app. Here is the link...https://photos.app.goo.gl/FsY4fxisXqTPtzAGA  You can see in the video the widget is labeled "Fertigation Interval."  Directly to the left is a Value Display that shows how much time is remaining in the interval.  You can see when I input a value into the Numeric Input the Value display to the left changes even before I tap the blue "send" button on the keyboard.  I have the log file available, let me know who to send it to.  Thanks

**Comment by doom369** [comment]
@Selah50 hello, do you use Android or iOS?

**Comment by Selah50** [comment]
@doom369 I am running Android 12 and version 1.3.5 of the Blynk app

**Comment by doom369** [comment]
@Selah50 thanks. Looking into it.

**Comment by Selah50** [comment]
@doom369 I just emailed you some more information about this issue.  Thanks.

**Comment by alexkipar** [comment]
@Selah50 we will fix this issue in the next version, I hope it will be available at the beginning of the next week.

**Comment by Selah50** [comment]
@alexkipar Thanks for the update, I appreciate it.

**Comment by Selah50** [comment]
@alexkipar Can you notify me when the fix is available?  When you say it will be in the next version, does that mean that the app will have to be updated from the app store?  Thanks.

**Comment by Selah50** [comment]
@doom369 Any ETA on when this issue might be fixed?  My current work around is a step slider.  The only issue with that is that on android devices you are able to see the value of the slider and on iOS devices you can't see the value. So I have to also have a value display directly above the slider.  It's confusing for the people who have purchased my device.  Thanks.

**Comment by alexkipar** [comment]
@Selah50 new version should be available to update

**Comment by Selah50** [comment]
@alexkipar @doom369 The issue still persists on my android device.  I uninstalled and installed the version that is available on the google play store.  Here is a video taken this morning.  Watch the value display to the left of the numeric input update from hardware as I am typing in values.  This shouldn't update until I tap the "send" button. https://photos.app.goo.gl/MymodQSCeSS8f5mX6

**Comment by alexkipar** [comment]
@Selah50 which version of the app?

**Comment by Selah50** [comment]
@alexkipar The version I installed from the app store says 1.3.5

**Comment by alexkipar** [comment]
It should be 1.3.6, I'll check why it it still not available

**Comment by Selah50** [comment]
> 

Thanks, I appreciate it.

**Comment by alexkipar** [comment]
@Selah50 Looks like the latest update should be finally available everywhere

**Comment by Selah50** [comment]
@alexkipar Thank you, I saw that this morning!  Appreciate it.

**Comment by doom369** [comment]
I think we can close.
