### ISSUE TITLE
Blynk can't connect to the server

### ISSUE THREAD

**Issue by TheodosiosKatis** [blynkkk/beta#220]
Hey. I'm doing this simple steps (https://iotdesignpro.com/projects/iot-controlled-led-using-raspberry-pi-and-blynk-app) to run a led via blynk server. But when i try to connect to the server with my auth-token then says invalid auth token. What's wrong?

**Comment by blynkkk** [comment]
Hi, questions like that can be answered on our forum: https://community.blynk.cc . Please use search, and if there is no answer, please create a new topic. Thanks!
