### ISSUE TITLE
Blynk.setProperty not working

### ISSUE THREAD

**Issue by Johnep101** [blynkkk/beta#221]
Hi,
Im trying to set the "Label" property of a segmented switch in Blynk 2.
The switch works as expected but I can't seem to change the menu titles as indicted in the documentation.
I'm using 'Blynk.setProperty(V4, "Labels", "A", "B","C");'  
But the labels just remain as labeled as written in the app.
im using IOS 15.2.1 on an iPad.

 is it possible to also change the name of the switch? (I want to write a multi language app such that tiles and labels can be changed by a switch.)

thanks

**Comment by doom369** [comment]
@Johnep101 hello, "labels" should be fully lowercase.

`Blynk.setProperty(V4, "labels", "A", "B","C");`

What doc did you use?

**Comment by Johnep101** [comment]
Hi Dmitriy,
Thank you my mistake, I used the on line docs but didn’t spot the lower case🤯🤯
All working perfectly👍
