### ISSUE TITLE
App needs to be killed and restarted to make new Datastreams available

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#23]
Android device: Nexus 7 running Android 6.0.1
Blynk app version 1.0.6

After adding new datastreams to a template and saving with the "Update x active device(s)" these datastreams aren't immediately available to assign to widgets.
The only way to overcome this seems to be t6o kill the app and re-open it, at which point the datastreams become available for selection.

Pete.

**Comment by Peterkn2001** [comment]
I'm nit sure why this would be classed as an enhancement. If you add a datastream and update the devices associated with that datastream then I wouldn't expect to have to kill the app and re-launch for that datastream to become available within the app.

Pete.

**Comment by doom369** [comment]
@Peterkn2001 because this is how most of the systems work. For example, go to let's say Facebook, open 2 tabs, and post in one tab, you'll see no update in the second tab until you do the update manually.

"force close" is not the right way to do that. So just refreshing the tiles somehow should fix that.

**Comment by alexkipar** [comment]
@doom369 @Peterkn2001 I'm adding refresh of datastream on any open of datastreams picker - it will fix this issue.

**Comment by doom369** [comment]
@alexkipar I don't think that's the best idea... Maybe it would be better to send an update event to the app. Otherwise, you'll do a lot of call during the typical setup

**Comment by alexkipar** [comment]
should be fixed in 1.0.7 version

**Comment by alexkipar** [comment]
@doom369 I will add later some timeout checks, for now, it would be better not to restart the app.

**Comment by Peterkn2001** [comment]
Tested, issue is fixed in 1.0.7

Issue can be closed - many thanks,

Pete,
