### ISSUE TITLE
Overlapping Widgets

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#24]
Android device: Nexus 7 running Android 6.0.1
Blynk app version 1.0.6

I've discovered that it's possible to overlap one widget on another, and I guess that this isn't an intended feature?

In this example, I've dropped a Value widget on top of a Horizontal Slider...

![image](https://user-images.githubusercontent.com/35718564/112857201-8417f480-90a8-11eb-894b-88fb91818061.png)

This is how it looks in "run" mode, the Value widget is partially obscured by the Slider, even though the Value widget seems to have been dropped on top of the slider...

![image](https://user-images.githubusercontent.com/35718564/112857167-7c585000-90a8-11eb-9a8f-d76a7bab81f1.png)

**Steps to re-create...**

This only seems possible when the slider widget is moved to its new position without exiting edit mode, then the value widget is moved over the top. Even then, it's sometimes tricky to get the positioning correct.

As a side issue (but possibly related?), I am actually having lots of problems positioning widgets accurately. I'm assuming that this is because my Android tablet is old and slow (a bit like me!). The "shadow" of the widget being moved - which indicates the location that the widget will occupy when it's released - lags behind the movement of the widget. Sometimes it can take several seconds, or require additional movement of the widget, before the shadow catches-up.
Even then, the widget may not actually land where I'm expecting when it's released.

Pete.

**Comment by alexkipar** [comment]
@Peterkn2001 This only seems possible when the slider widget is moved to its new position without exiting edit mode:

Does it mean:
1. Add widget
2. Move it immediately after adding
3. Exit dev mode?

**Comment by alexkipar** [comment]
@Peterkn2001 I will check the lags on my Nexus 7 - it is possible that a huge dashboard can lead to such issues.

**Comment by Peterkn2001** [comment]
Okay, after lots of playing around, I can now reproduce this about 50% of the time.

What seems to be required (although this may not be 100% accurate)...

Enter dev mode.
Move widgets from their existing position to a new position that was previously unoccupied.
It seems that two widgets need to be moved to new locations, and that they need to touch each other.
Then, move a third widget over the last one, and it can be made to overlap.

It seems that I was wrong when I thought that exiting and re-entering dev mode blocked further overlapping of widgets without starting the process over again.. If you watch the attached video to the end you'll see that the LED widget can still be overlapped on the Value widget...

https://www.youtube.com/watch?v=05tJW02UFtc

I've also seen a situation where I went to the Widget Box and added a new widget, which appeared in the top left hand corner of the screen, overlaying a Value widget that was already in that top left hand corner, but I've not been able to reproduce that again!

When you watch the video you'll see what I mean about having problems positioning widgets. When I move the labelled value widget down and try to position it against the left hand edge of the screen it refuses to drop in to that location.

Pete.

**Comment by alexkipar** [comment]
Pete,

It seems the drag is improved - no visible lagging on my Nexus 7. Also the bug with overlap should be fixed too. New build 1.0.8 with a fix should be available soon

**Comment by Peterkn2001** [comment]
Tested with 1.0.8 and dragging is greatly improved. I've had numerous attempts and can't re-create the overlapping widget issue again with the new version, so I think it's safe to say that it's fixed, and the issue can be closed.

Thanks.

Pete.
