### ISSUE TITLE
Notifications sometimes needs phone unlock to work

### ISSUE THREAD

**Issue by spiutm** [blynkkk/beta#25]
Notifications sometimes needs phone unlock to work, like 50% in rest works fine, fast response

scene: notification on temperature rise or drop set on specific range

**Comment by alexkipar** [comment]
@spiutm can you add your smartphone model and android os version?

**Comment by spiutm** [comment]
samsung note 9 android 10

**Comment by spiutm** [comment]
any fix?

**Comment by alexkipar** [comment]
@spiutm I can't reproduce this issue on my side it requires longer investigation

**Comment by alexkipar** [comment]
@spiutm please check app's battery optimization settings on your device, Settings -> Apps -> Blynk Beta -> Battery - it should work on most Android10 and later devices. You can try to set it to 'Do not optimize' and verify the behavior, there is probably a strict optimization for app's background work on your Samsung and it more frequently blocks even high priority notifications.

**Comment by spiutm** [comment]
i will try

**Comment by spiutm** [comment]
at first try it worked, but need to further test on long run, i will return with update

**Comment by spiutm** [comment]
works as intended, ty
