### ISSUE TITLE
Labelled Value Widgets - text added after label is bold

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#26]
App version 1.0.7

Text added after the label value appears bold, as in the screenshots below..

![image](https://user-images.githubusercontent.com/35718564/112887617-4bd5dd80-90cb-11eb-83d6-7017c85620aa.png)

Pete.

**Comment by alexkipar** [comment]
@Peterkn2001 different font is correct. on such suffixes - there is no need to add them in formatting. you can set up Data Stream unit - and as a result, you will have this suffix auto-added to the value, plus it will be better formatted as half text size.

**Comment by doom369** [comment]
@alexkipar but why it is bold anyway?

**Comment by alexkipar** [comment]
@doom369 it is no bold. it is just thicker than decimals font, which is super fin.
