### ISSUE TITLE
Enhancement Request - Add default text colour to picker

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#27]
The default text colour appears to be a very dark blue (38 41 87 according to Photoshop), but this colour isn't available as one of the presets in the colour picker.
Although it's possible to add this as a custom colour, that's difficult if you aren't able to work-our what the RRGGBB value is.

Pete.

**Comment by alexkipar** [comment]
@Peterkn2001 added our primary and secondary colors to the picker. in the future, we will improve this dialog with a better custom color palette. 

new build 1.0.8 with a fix should be available in an hour at max

**Comment by Peterkn2001** [comment]
Confirm fixed in 1.0.8

Can be closed - thanks.

Pete.
