### ISSUE TITLE
Label level lost color after change, dashboard

### ISSUE THREAD

**Issue by spiutm** [blynkkk/beta#28]
Label level lost color after change, dashboard

had it on blue, wanted it green, change it and now has no color

**Comment by alexkipar** [comment]
@spiutm android app or web dashboard?

**Comment by spiutm** [comment]
web dashboard

**Comment by Peterkn2001** [comment]
Is that the same as this: #19

Pete,

**Comment by spiutm** [comment]
yes sorry didn't seen that
ill close

**Comment by doom369** [comment]
@spiutm fix deployed. Please let me know is still reproduced. It may require refreshing your browser page.

**Comment by spiutm** [comment]
works fine now,ty
