### ISSUE TITLE
Error Generating Device Report

### ISSUE THREAD

**Issue by thomoray** [blynkkk/beta#29]
Not able to generate the report in JSON format calling Get Device Report

File format worked ok with the below settings but when changing to JSON as per docs I received an error.

![image](https://user-images.githubusercontent.com/12146573/112893874-f29b9780-9126-11eb-9dfc-bb41cffc519a.png)

**Comment by doom369** [comment]
@thomoray should be fixed now. Could you please check?

**Comment by thomoray** [comment]
Retested and works if I don't add dataStreamId or pin as options. If I remove this option then it generates okay.

**Comment by doom369** [comment]
@thomoray the fix is deployed. Now should be fixed.
