### ISSUE TITLE
On Android, in SuperChart some colors of Datastreams does not show up  

### ISSUE THREAD

**Issue by rmznsy** [blynkkk/beta#32]
These two colors does not visible before the text. İts just empty.

Android App: 1.0.8
S10e Android 11

![Screenshot_20210330-090047_Blynk Cloud](https://user-images.githubusercontent.com/81516108/112942732-42835a00-9139-11eb-8ce5-1c80c1461669.jpg)
<img width="598" alt="Screen Shot 2021-03-30 at 09 19 48" src="https://user-images.githubusercontent.com/81516108/112942759-4adb9500-9139-11eb-9b31-3f7f8f78ec86.png">

**Comment by alexkipar** [comment]
@rmznsy they are not supported. it is a bug that they are visible

**Comment by alexkipar** [comment]
should be fixed in 1.0.9 build
