### ISSUE TITLE
Problem extracting Blynk.Air shipment reports

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#33]
Downloaded Blynk.Air shipment reports can't be extracted using the Windows 10 built-in Zip functionality - a "parameter is incorrect" message is generated...

![image](https://user-images.githubusercontent.com/35718564/112950346-16b0a600-9132-11eb-98e8-3a382b59e126.png)

Extracting the file using WinRar was successful.

Pete.

**Comment by doom369** [comment]
It's because of the colon. As quick fix, you can replace it with something else.

**Comment by Peterkn2001** [comment]
> you can replace it with something else
You can't change the name of a file within a .zip archive without extracting it first - at least not with the W10 built-in .zip extraction tools.

Pete.

**Comment by doom369** [comment]
deployed

**Comment by Peterkn2001** [comment]
Tested and working - thank you.

Pete.
