### ISSUE TITLE
Can’t edit templates on ipad

### ISSUE THREAD

**Issue by Johnep101** [blynkkk/beta#35]
Maybe this is just a safari issue but I can’t edit a template on my iPad, can’t drag/drop widgets
iPad Pro using safari and ios 14.4.1

**Comment by doom369** [comment]
@Johnep101 should be fixed now. Could you please check?

**Comment by Johnep101** [comment]
Hi Dmitriy,
I can now drag and drop items onto the template but can't edit or remove them.
Thanks.

**Comment by doom369** [comment]
@Johnep101 should be fixed. Please reopen if reproduced.
