### ISSUE TITLE
Superchart and refreshing

### ISSUE THREAD

**Issue by marminatix** [blynkkk/beta#37]
Hi.
Others on superchart:

Past data:
ANDROID: how to delete past data? or BETTER: how to save and/or delete past data? Zeroing the variable seems not working. APP version has a awful data download format. Could it be improved for easier speadsheet importing?
CLOUD: idem as ANDROID

Live Mode:
ANDROID: SOMETIMES, switching from 15 mins (or other higher) to LIVE, X axis doesn't flow in a reasonable time period or freeze. Need to change internet connection from WiFi to 4G and back to run again.
CLOUD: N/A

Updating OFFLINE-ONLINE status
ANDROID: Seems working well
CLOUD: Need to refresh (or to click) before offline to online status updates

Thanks
Marco

**Comment by doom369** [comment]
> how to delete past data? 

Could be done only on the web for now. @blynkkk FYI.

> APP version has a awful data download format. Could it be improved for easier speadsheet importing?

Do you mean beta or old version? Data format was changed in the BETA, you can check that in web interface.

> CLOUD: Need to refresh (or to click) before offline to online status update

Known issue - https://github.com/blynkkk/beta/issues/22. Will be fixed with next deploy.

**Comment by Peterkn2001** [comment]
A few more chart issues that I'll add in here...

Refreshing the web device dashboard always changes the timescale to "Last Hour", regardless of which timescale was show prior to the refresh.

Template view of web dashboard populates the chart and modules with data, but this bears no resemblance to the actual values shown in the device view (and would be even more confusing if there were multiple devices pushing different data). These template charts etc should remain unpopulated.

@marminatix to clear the data in the web dashboard, select the device and next to the device name and on/offline status at the top of the screen there are three dots. Click these dots and one of the options is "Erase Data".
Personally, I find this a bit confusing, as I'd half-expected this to wipe the sketch, credentials etc from the device, as you would with a lost phone, but that's not what it does.

Pete.

**Comment by doom369** [comment]
> Refreshing the web device dashboard always changes the timescale to "Last Hour", regardless of which timescale was show prior to the refresh.

I remember we fixed that if you switch between the device. But for a page refresh... We'll check if there is an easy fix.

> Template view of web dashboard populates the chart and modules with data, but this bears no resemblance to the actual values shown in the device view (and would be even more confusing if there were multiple devices pushing different data). These template charts etc should remain unpopulated.

That's was done on purpose to show how the graph might look like. As this template "edit" mode.

> Personally, I find this a bit confusing, as I'd half-expected this to wipe the sketch, credentials etc from the device

With dynamic provisioning, there are no more "device credentials". Now you have a device and you can change the token at any time. Via reprovisioning or via manual token update (available only for the super admin for now).

**Comment by alexkipar** [comment]
@marminatix you can't clear only graph data on mobile, but in device info screen you can remove all the data for a device.

**Comment by Peterkn2001** [comment]
>That's was done on purpose to show how the graph might look like. As this template "edit" mode.

It's one thing to give a simulated preview, but why would you populate the chart and modules with totally random, but correctly time-stamped data?
![image](https://user-images.githubusercontent.com/35718564/113130609-2bfe0100-9214-11eb-97e5-b4c8c9fdb54b.png)

which bears no resemblance to the actual data being received by the device...
![image](https://user-images.githubusercontent.com/35718564/113130974-87c88a00-9214-11eb-9d3e-cbb8e9997998.png)

It's just confusing in my opinion.

Pete.

**Comment by marminatix** [comment]
> > how to delete past data?
> 
> Could be done only on the web for now. @blynkkk FYI.
> 
> > APP version has a awful data download format. Could it be improved for easier speadsheet importing?
> 
> Do you mean beta or old version? Data format was changed in the BETA, you can check that in web interface.
> 
> > CLOUD: Need to refresh (or to click) before offline to online status update
> 
> Known issue - #22. Will be fixed with next deploy.

**Comment by marminatix** [comment]
_"Do you mean beta or old version? Data format was changed in the BETA, you can check that in web interface."_
I intended the old app version 2.7.28. Tried to import .csv in Excel or google sheets but looks not "obvious" nor easy.
I'm gently asking if the data export, when in the future it would be available, could be more rapidly and directly analyzed with common spreadsheet or BI software. Thanks

**Comment by doom369** [comment]
> I intended the old app version 2.7.28.

In that case, it was fixed already in the new Beta.

@Peterkn2001 regarding "changes the timescale to "Last Hour"," should be fixed. Coul
