### ISSUE TITLE
Superchart again

### ISSUE THREAD

**Issue by marminatix** [blynkkk/beta#38]
Hi.

ANDROID (Redmi NOTE 9 PRO)
Superchart on full screen with data (any resolution, horizontal device orientation).
Switch to another app while in full screen and horizontal device.
Back again to Blynk Beta
No more data to see and no way to retrieve graph: "No data yet"

Only way out I found: turn screen vertical again (or set superchart on "standard screen" mode).

Marco

**Comment by alexkipar** [comment]
Should be fixed in the latest version

**Comment by marminatix** [comment]
Solved!
