### ISSUE TITLE
Automation: setting trigger

### ISSUE THREAD

**Issue by marminatix** [blynkkk/beta#39]
Hi
Android
Automation
Set trigger
At the bottom of the screen the stepH appears with the lower value at the center.
If you try to manually set via gboard, the system refuses to accept the input.
Or was it my fault?
Marco

**Comment by alexkipar** [comment]
@marminatix Can you provide a screenshot? What type of datastream is used for this trigger?

**Comment by marminatix** [comment]
![IMG_20210404_135525](https://user-images.githubusercontent.com/81511771/113507999-e318b600-954d-11eb-8f30-0bbe22de255f.jpg)
![IMG_20210404_135538](https://user-images.githubusercontent.com/81511771/113508002-e3b14c80-954d-11eb-9115-0b3ebd99d746.jpg)
![IMG_20210404_135551](https://user-images.githubusercontent.com/81511771/113508003-e449e300-954d-11eb-975e-232449bae97e.jpg)
![IMG_20210404_135603](https://user-images.githubusercontent.com/81511771/113508004-e4e27980-954d-11eb-98c7-27298a2c2528.jpg)
![IMG_20210404_135613](https://user-images.githubusercontent.com/81511771/113508005-e4e27980-954d-11eb-8ef3-e430344e386e.jpg)
![IMG_20210404_135707](https://user-images.githubusercontent.com/81511771/113508006-e57b1000-954d-11eb-9113-8be048757b40.jpg)

**Comment by marminatix** [comment]
The stream is a temperature value. When u try to set the trigger via gboard it doesn't accept the entry. Must use the (+) or (-).

**Comment by alexkipar** [comment]
@vshymanskyy got it, seems it is an issue with scroll - the list should scroll to the input field below - is it scrollable?

**Comment by marminatix** [comment]
You're right!
Now it works.
