### ISSUE TITLE
The link to the documentation  to blynk.360  does not work for me

### ISSUE THREAD

**Issue by jxl77** [blynkkk/beta#4]
The link to the documentation  to blynk.360 
given here 
https://docs.blynk.io/en/platform-overview/products-and-services/products
   does not work 
https://docs.blynk.io/en/ssrSpaces/spaces/en

**Comment by doom369** [comment]
@Mark-Pan this link:

![screenshot-docs blynk io-2021 03 27-11_22_30](https://user-images.githubusercontent.com/1536494/112716380-bed62d00-8eee-11eb-9055-858ed40093e3.png)

**Comment by jxl77** [comment]
This is where I clicked 
![bugdoc](https://user-images.githubusercontent.com/81445092/112718146-5c326080-8ef1-11eb-8478-89b42a4746c7.jpg)

**Comment by Mark-Pan** [comment]
Links are fixed. (Gitbook issue)

@jxl77 clear your browser's cache and check on your side please.
