### ISSUE TITLE
Video Streaming Widget :-(

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#40]
I've been trying to get the video streaming widget working with a local network stream from one of my Reolink CCTV cameras, which is in RTSP format.

Testing...
Using the current (non-beta) version of the Blynk app on iOS (version 2.26.6) the video stream works perfectly.
Opening the same project, with the video streaming widget in it, on Android version 2.28.8 the video stream doesn't play and I get a message "Unable to instantiate decoder OMX.qcom.video.decoder.avc"

Adding the same url to the Android beta 1.0.10 app doesn't play either. The widget shows "No video stream available :(" and flashes with a black image for a fraction of a second every 6 seconds.

Also, tapping on the widget in "play" (non dev) mode brings up a dialogue box which allows the user to see the url (including embedded username and password) and aparently edit the url as well. I'm assuming that this isn't untended behaviour?

Logs from both versions of the Android app sent.

Pete.

**Comment by alexkipar** [comment]
@Peterkn2001 I had not enabled exoplayer support for the video widget yet in beta - will do it with the next release. But if the 2.28.8 had not been able to play it - probably beta would not be able too. any video format description for RTSP?

**Comment by alexkipar** [comment]
@Peterkn2001 have you tried the latest stable 2.28.x version with VLC library implementation?

**Comment by Peterkn2001** [comment]
>any video format description for RTSP?

It's a standard video format.... https://en.wikipedia.org/wiki/Real_Time_Streaming_Protocol
but the info button for the widget says that RPSP is supported anyway...

![image](https://user-images.githubusercontent.com/35718564/113516469-5cc29b00-9572-11eb-8029-932e7799119b.png)


>have you tried the latest stable 2.28.x version

I assume you mean 2.27.x version?
I just left the beta channel and re-installed the latest stable version which is 2.27.28 and that doesn't work with the RTSP stream that is working in iOS. I just get a white screen with "No video stream available :(" in very pale yellow text.

Pete.

**Comment by alexkipar** [comment]
iOS app uses different video library than Android app. on Android app we have vlc on 2.27.x and exoplayer with not stable rtsp support on 2.28.x - I don't think we will implement some third option for android app. 
I'm waiting for a stable rtsp implementation in exoplayer - it is the only stable video player capable of handling several video views. vlc implementation is the cause of most blynk app's crashes and anr, according to crash statistics.

RTSP is a streaming protocol, what type of video stream is inside: h264, mjpeg, etc? does it have audio or not?

**Comment by Peterkn2001** [comment]
>RTSP is a streaming protocol, what type of video stream is inside: h264, mjpeg, etc? does it have audio or not?

It's FFMPG, with audio, and I have a choice of the _main and _sub streams.
_main is currently set to 2560*1920 @ 25fps
_sub is set to 640*480 @ 7fps.

Both streams work fine with iOS, but neither with 2.27.28

Pete.

**Comment by alexkipar** [comment]
I've added ExoPlayer RTSP support to the Video widget in the latest build.

**Comment by alexkipar** [comment]
I'm also working on ffmpeg video support - I suppose the next build will be with it.

**Comment by Peterkn2001** [comment]
Just testing things in 1.0.11 and the video streaming widget refuses to remember the url of the video stream.
If I paste it into the url field then hit the left exit arrow icon, then return to the video stream settings my url has disappeared.

Testing the provisioning stuff next, I'll send logs after that if you wish.

Pete.

**Comment by alexkipar** [comment]
@Peterkn2001 thanks, there is no need for logs here.

**Comment by alexkipar** [comment]
@Peterkn2001 I've just uploaded the 1.0.12 version - it uses FFmpeg in the video widget. please check it with your stream

**Comment by Peterkn2001** [comment]
Yay! that works!!

A couple of observations....

It works well with the lower resolution stream. The higher resolution stream buffers (with the three juggling balls) quite frequently, but this may be my Nexus device. Forcing TCP transport seems to improve this a little.

Hitting the 'play' icon at the bottom left of the widget whilst in dev mode causes an "Unfortunately Blynk Beta has stopped - Report/OK" dialogue.
Hitting OK recovers back to the templates screen in dev mode.
Hitting Report bring-up a Google "Send feedback..." dialogue.

I tried adding a second video streaming widget, and only the last video widget that was added is working (the original working widget shows a grey screen). Hitting any of the on-screen controls for the first widget (play/stop, expand to full screen) are actually controlling the second widget.
Deleting the second widget makes the first widget function correctly again.

Tapping the widget (in normal "run" mode) bring-up an overlay showing the play/stop, expand to full screen etc) but it also shows the URL of the video stream. This is an issue for me, as the URL contains the username and password for the camera in plain text.

I've sent you the logs, in case they help with the "Unfortunately Blynk Beta has stopped - Report/OK" message.

Pete.

**Comment by alexkipar** [comment]
@Peterkn2001 

Good. It looks promising, probably I will port this ffmpeg implementation to the older blynk app 2.28.x too.

In dev mode that controller should not be available. I'll check the report and will hide it.

**Comment by alexkipar** [comment]
@Peterkn2001 I've removed URL text and fixed the crash in a new version- it should be available soon

**Comment by Peterkn2001** [comment]
@alexkipar I've tested it and it's fine - thanks.

Should we close this issue now?

Pete.
