### ISSUE TITLE
Time-Line for Items

### ISSUE THREAD

**Issue by JimE007** [blynkkk/beta#41]
When will the iOS App be released?   Can it run concurrently with the current APP?

When will the pricing model be released?

When will the current Blynk Cloud and Apps be discontinued?

**Comment by doom369** [comment]
> When will the iOS App be released? 

Already done.

> Can it run concurrently with the current APP?

Yes

> When will the pricing model be released?

In 1-2 months.

> When will the current Blynk Cloud and Apps be discontinued?

At some points after the Blynk 2.0 public launch.
