### ISSUE TITLE
Cant download beta android app

### ISSUE THREAD

**Issue by Smartnitz** [blynkkk/beta#42]
Hey,

I was invited to the beta and allready have an account for the new blank dashboard. 

Unfortunately I cant download the beta android app for my smartphone. The link I got in the invitation email is simply not working and in the google play store I can only find the old non-beta app.

Were can I dowload the app? :(

**Comment by alexkipar** [comment]
@Smartnitz have you tried this link: https://play.google.com/apps/testing/cloud.blynk ?

can you provide your email?

**Comment by Smartnitz** [comment]
this link gets me an error message after logging in with my google account. It says the test version of this app hasent been released or is not available for my account.

The issue there might be that I used my yahoo-mail account to sign up for the blynk beta. And my google account is a different one of course. 

Unfortunately I couldnt find a way to send you a private message on github or your email adress. So I will just post my email  here publicy and hope that nobody messes around with it :P

I signed up for beta with this: martinuhlmann@yahoo.de
this is my google account: uhlmann.martin@gmail.com

**Comment by alexkipar** [comment]
@Smartnitz yep, that's because of yahoo email in sign up list

**Comment by alexkipar** [comment]
@Smartnitz you gmail account has been added to testers list - so in a minute that link should lead you correctly.

**Comment by Smartnitz** [comment]
Thank you very much. It worked now :)

**Comment by OmarQT** [comment]
I have the same issue even though I'm using the same email address where I received the invitation, can you assist?

**Comment by alexkipar** [comment]
@OmarQT what does play store show you when you try the link above?

**Comment by OmarQT** [comment]
This is what I see when I try the link
[image: image.png]

**Comment by alexkipar** [comment]
@OmarQT, the image hadn't attached( can you also provide your email - I will verify if it is in the access list

**Comment by OmarQT** [comment]
![unnamed](https://user-images.githubusercontent.com/83025203/115902165-bf97ab80-a427-11eb-9b3d-c08ffa4c92f1.png)
Sorry about that @alexkipar , let's see if works this time, my email is omar.qtorres@gmail.com

**Comment by alexkipar** [comment]
@OmarQT it seems this email got lost somehow, I've just added it - the link should work now

**Comment by OmarQT** [comment]
Thankyou @alexkipar all good now!
