### ISSUE TITLE
Invalidate Data settings not working correctly

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#43]
I added "Invalidate Data" settings to a datastream like this:

![image](https://user-images.githubusercontent.com/35718564/113871612-fd9b9b00-97aa-11eb-9dc5-b1b5bd543bed.png)

but instead of the widgets showing "--" after 10 seconds of no data, it seems to take around 12 to 14 hours before the existing values are replaced with "--" when no data is being sent to the datastream.

**Edited to add** - the data is being sent via an API call. Datastreams where data is being sent via Blynk.virtialWrites appear to work correctloy.

Pete.

**Comment by doom369** [comment]
@Peterkn2001 invalidation doesn't work in real-time. However, open/close web/app should show the invalidated feature.
