### ISSUE TITLE
Sliders in Anroid dont show current value

### ISSUE THREAD

**Issue by Smartnitz** [blynkkk/beta#45]
Hey,

I noticed the Sliders widgets in the Anroid app dont show the current value and there also is no option anymore to show these values. The option to the change the decimals has also gone missing :(

**Comment by alexkipar** [comment]
@Smartnitz that's expected behavior, You can always add any display widget of your choice with the same data stream as Slider to see the values.

**Comment by alexkipar** [comment]
@Smartnitz about decimals: all formatting options are now on the side of the data stream - you can set up it and the app will use its formatting.
