### ISSUE TITLE
How to share cloud device?

### ISSUE THREAD

**Issue by marminatix** [blynkkk/beta#46]
Hi.
An industrial customer ask me to share the dashshboard of my "beta" device with him.
Obviously, he doesn't need to edit the properties but only to "read" the labels and the charts and to interasct with the widgets.
Is it possibile?

Thank you.
Marco

**Comment by doom369** [comment]
@marminatix yes. you need to invite him to your org for that. On invite provide him with required role (`user` role to view but not edit/control your devices)

![screenshot-blynk cloud-2021 04 08-21_25_56](https://user-images.githubusercontent.com/1536494/114078136-3cb41400-98b1-11eb-9d9f-418f9961ddd3.png)

**Comment by marminatix** [comment]
Beautiful!
