### ISSUE TITLE
Recycled widgets re-appear again

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#5]
Android device: Nexus 7 running Android 6.0.1

When removing a widget from the app by dragging it over the "recycle" logo it disappears, but when an existing widget is edited, or a new one added, the recycled widget re-appears.
Opening the unwanted widget and scrolling down to "Delete" works as expected.

**Gauge widget added...**

![Screenshot_20210327-005550](https://user-images.githubusercontent.com/35718564/112704359-42adfc00-8e92-11eb-86e9-62ae258994b1.png)

**Gauge Widget recycled...**

![Screenshot_20210327-005654](https://user-images.githubusercontent.com/35718564/112704370-4e99be00-8e92-11eb-80cd-d8949ad5e8b2.png)

**Gauge widget no longer visible...**

![Screenshot_20210327-005705](https://user-images.githubusercontent.com/35718564/112704375-535e7200-8e92-11eb-8c26-87eab0ae4ae6.png)

**Gauge widget re-appears after editing the button widget...**

![Screenshot_20210327-005713](https://user-images.githubusercontent.com/35718564/112704386-578a8f80-8e92-11eb-9d88-38fe596829dd.png)

**Comment by alexkipar** [comment]
@Peterkn2001 should be fixed in a new build

**Comment by Peterkn2001** [comment]
Has been fixed in version 1.0.6 of the app.

Can be closed now - thanks.

Pete.
