### ISSUE TITLE
Minor error in documentation

### ISSUE THREAD

**Issue by Smartnitz** [blynkkk/beta#52]
hey,

Not sure if this is the right place to mention this, but I found a minor error in the description.

![grafik](https://user-images.githubusercontent.com/82087142/114423040-147d2b80-9bb7-11eb-9886-aee9be7a237f.png)

I think its supposed to be:

https://{server_address}/external/api/logEvent?token={token}&code={event_name}

**Comment by doom369** [comment]
@Smartnitz thanks.
@Mark-Pan please fix.

**Comment by Mark-Pan** [comment]
@Smartnitz thanks.
@doom369 fixed.
