### ISSUE TITLE
Widget Titles are now all CAPITALS!!

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#54]
Previously, in the Android beta app widget titles were displayed as typed - in upper or lower case.
Now, regardless of how the title is typed, it is displayed in upper case.
This appears to have been done to coincide with the release of the iOS version of the app, where the behaviour is the same.

Is there any way around this?

There are many situations, especially when adding widget labels to LEDs where only a short title is possible, when a mixture of mixed upper and lower case can be much more legible and meaningful than the same text all in capitals.

Pete.

**Comment by alexkipar** [comment]
@Peterkn2001 I'm uploading a new version soon, the previous build had the wrong app's theme.

**Comment by Peterkn2001** [comment]
Now fixed in iOS 3.1.0(15) and Android 1.0.14(26)

Thank you!

Pete.
