### ISSUE TITLE
Reset password is broken

### ISSUE THREAD

**Issue by Saurman** [blynkkk/beta#55]
After clicking reset password link from email i am redirected to a dashboard

**Comment by doom369** [comment]
@Saurman hello, could you please clarify - do you open the link from the mobile or web?

**Comment by Saurman** [comment]
Web

**Comment by doom369** [comment]
@Saurman in that case I'm not sure I understand the issue. "Reset" password link should move you to the "reset password" screen. That's not the case for you?

**Comment by Saurman** [comment]
No, it just opens an initial cloud dashboard for me

**Comment by doom369** [comment]
@Saurman so like you are logged into it?

**Comment by Saurman** [comment]
Yes

**Comment by doom369** [comment]
@Saurman Did you logout from the web?

**Comment by Saurman** [comment]
Should i for reset to work?

**Comment by doom369** [comment]
@Saurman if you want to reset the password you can do that from the web:
![screenshot-dash-qa blynk cc-2021 04 14-20_57_31](https://user-images.githubusercontent.com/1536494/114757125-23eda780-9d64-11eb-92e6-0f72502fc671.png)

For reset flow you have to be logged out. Otherwise you are not actually "forgot the password"

**Comment by Saurman** [comment]
Logout from cloud worked, was able to reset password. Icons are still broken in Safari
<img width="313" alt="Screenshot 2021-04-14 at 22 56 48" src="https://user-images.githubusercontent.com/1107926/114770999-bf871400-9d74-11eb-876b-437e1cf29a39.png">

**Comment by Saurman** [comment]
also, is there a way to migrate a project from public app?

**Comment by doom369** [comment]
> Icons are still broken in Safari

Could you please check the browser console for the errors? Those images are delivered from the CDN, so looks like it were failed to download unless this is something else.

**Comment by Saurman** [comment]
> Could you please check the browser console for the errors? Those images are delivered from the CDN, so looks like it were failed to download unless this is something else.

[Error] Origin https://blynk.cloud is not allowed by Access-Control-Allow-Origin.
[Error] Failed to load resource: Origin https://blynk.cloud is not allowed by Access-Control-Allow-Origin. (Linearicons.woff2, line 0)

**Comment by doom369** [comment]
@Saurman that's strange. Looks like a browser bug to me, as `allow origin` header is correct. What Safari version do you have?

**Comment by Saurman** [comment]
Yes, that errors was not on a dashboard home screen, this screenshot is:
<img width="1430" alt="Screenshot 2021-04-15 at 13 51 36" src="https://user-images.githubusercontent.com/1107926/114858093-b5efc180-9df1-11eb-8547-9d30fcafdbd7.png">

**Comment by Saurman** [comment]
Safari 14.0.3

**Comment by thanxx** [comment]
@Saurman can you please disable extensions for Safari, clear cache, and try again?

**Comment by doom369** [comment]
@Saurman please run the next command:

`curl -IL -X'GET' -H'Origin: https://blynk.cloud' https://static-fonts.nyc3.cdn.digitaloceanspaces.com/Linearicons.woff2`

**Comment by Saurman** [comment]
> @Saurman please run the next command:
> 
> `curl -IL -X'GET' -H'Origin: https://blynk.cloud' https://static-fonts.nyc3.cdn.digitaloceanspaces.com/Linearicons.woff2`


HTTP/1.1 200 OK
Date: Thu, 15 Apr 2021 17:09:19 GMT
Connection: Keep-Alive
Cache-Control: max-age=344694
Content-Length: 159416
Content-Type: font/woff2
Last-Modified: Wed, 15 Jan 2020 13:53:29 GMT
Accept-Ranges: bytes
x-rgw-object-type: Normal
ETag: "5820aea7e44a2bac55288f21a28167fc"
x-amz-request-id: tx0000000000000b7d6036d-0060747b35-b7a28f3-nyc3b
access-control-allow-origin: *
access-control-allow-methods: GET
access-control-max-age: 0
strict-transport-security: max-age=15552000; includeSubDomains; preload
Vary: Access-Control-Request-Headers,Access-Control-Request-Method,Origin
X-HW: 1618506559.dop006.wa1.t,1618506559.cds011.wa1.shn,1618506559.dop006.wa1.t,1618506559.cds010.wa1.c

**Comment by doom369** [comment]
That's means that CORS headers are correct and you should not see the above error in the browser. I have no ideas right now what that could be.

**Comment by Saurman** [comment]
> That's means that CORS headers are correct and you should not see the above error in the browser. I have no ideas right now what that could be.

works fine in Chrome on latest OSX so i assume it needs some attention from Safari side on your end

**Comment by doom369** [comment]
I found few bug reports for Safari. We were able to reproduce only with the mobile Safari version. Most likely this is a Safari bug. We'll try try to find some workarounds.
