### ISSUE TITLE
Issues with iOS app when using Image Button widget

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#57]
iOS app version 3.1.0(14) on iPhone 11 (iOS 14.4.2)

After adding image URLs for Off and On states, tapping the image in edit mode clears the url and the image and they have to be re-entered.

In Android 1.0.13 the url isn't displayed (which it should be), but at least the image is retained.

Android app has a "Refresh" button at the bottom of the screen where the url is entered, iOS has an "Add Image" button.

Pete.

**Comment by eepetrash** [comment]
Please check the 3.1.0 (17) build

**Comment by Peterkn2001** [comment]
Fixed in iOS 3.1.0 (17) and missing URL fixed in Android 1.0.14

Thanks!

Pete.
