### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by davidmariag** [blynkkk/beta#61]
Two things. 
Is there a “beta” section in the forum to discuss these things?
I get a “server not available” error in the iOS app. 

![10AF44C1-20F6-437A-9288-3E383A0C916B](https://user-images.githubusercontent.com/61051937/115004016-0a0cab80-9eaf-11eb-98ae-e763cecc82a5.jpeg)

Is this a generic message to all errors? Incorrect password username etc.?
The reason I ask is I setup the account in blynk360 and I am assuming that is the same account as the app.

**Comment by doom369** [comment]
> The reason I ask is I setup the account in blynk360 and I am assuming that is the same account as the app.

Yes. It's the same account.

> Is this a generic message to all errors? Incorrect password username etc.?

Could be. @eepetrash please take a look.

**Comment by eepetrash** [comment]
@davidmariag after failure to login, please go to initial screen, touch and hold on the Blynk logo and send us logs to take a look.

**Comment by doom369** [comment]
@davidmariag could you please login again? What region are you in?

**Comment by eepetrash** [comment]
@davidmariag 
Thanks for the logs.
There is a new build in Testflight - 3.1.0 (19) with additional networking logging.
Please update, try to login, and send us new logs.

**Comment by davidmariag** [comment]
I am in Ethiopia Africa but my device content filter maybe routed through
USA.

**Comment by davidmariag** [comment]
Resent logs. Issue persists.

**Comment by doom369** [comment]
@davidmariag thanks for the additional info. Looks like you are using some proxy. Is that correct? It seems that those proxy doesn't propagate iOS client header correctly and that's why you can't connect.
Is that possible to turn if off for the Blynk app?

**Comment by davidmariag** [comment]
That would make sense that it is using a proxy. No it is not possible to
turn it off and on. The company managing the ground control is in America.

**Comment by doom369** [comment]
@davidmariag ok. Added even mode logging. Could you please try again?

**Comment by davidmariag** [comment]
Is it a new version or existing?

**Comment by doom369** [comment]
@davidmariag existing. I added more logging on the server-side to prove some ideas about this issue.

**Comment by doom369** [comment]
@davidmariag is that proxy installed on your phone? Or it's setuped?

**Comment by davidmariag** [comment]
The phone has to be wiped and it is setup in the phone setup process
through iTunes.

Here is the company’s email. ***@***.***

**Comment by davidmariag** [comment]
It’s a configuration profile.

**Comment by doom369** [comment]
@davidmariag okey. Looks like we can't do much here. Proxy truncates required headers so not much options from our side. You need to either remove the proxy or and whitelist some hosts.

**Comment by davidmariag** [comment]
The issue persists. Will it be fixed in the public release.

**Comment by doom369** [comment]
No. As I said - proxy truncates the headers required for establishing the connection. So we can't do much here.

**Comment by davidmariag** [comment]
Sorry I missed that message. What is the host that I should ask them to
whitelist?

David

**Comment by doom369** [comment]
blynk.cloud

**Comment by davidmariag** [comment]
Ok they have whitelisted the app and now it works.
