### ISSUE TITLE
Gauges

### ISSUE THREAD

**Issue by davidmariag** [blynkkk/beta#67]
If you copy a gauge in the app the Virtual pin in the settings copies as expected but the V# doesn’t display on the gauge unless you change to a different pin and back again 
![033B2D9A-0278-4F36-AE0E-8EA814F053FB](https://user-images.githubusercontent.com/61051937/115966903-5b184180-a538-11eb-9fce-44caf3b6ccc7.png)

**Comment by davidmariag** [comment]
Added comment. I would expect the gauges should be like the button pictured. When you go into development mode the V# isn’t displaying. 
![FF29533E-71F7-415A-B9AF-F354962E9123](https://user-images.githubusercontent.com/61051937/115969997-74c18500-a548-11eb-875c-1d873f8ad77e.png)

**Comment by eepetrash** [comment]
Copying the detastream selection was actually a bug. Everything except detastream selection should be copied.

Showing pin fixed in Blynk beta 3.1.0(20)
