### ISSUE TITLE
Android app lost

### ISSUE THREAD

**Issue by whogarden** [blynkkk/beta#73]
I had to restore my smartphone to factory settings, 
But now that it's done I can not find the android app to restart testings.
What can I do please?

**Comment by alexkipar** [comment]
@whogarden it should be available by the link: https://play.google.com/store/apps/details?id=cloud.blynk

**Comment by whogarden** [comment]
There is nothing here https://play.google.com/store/apps/details?id=cloud.blynk
The answer is : Désolé, impossible de trouver l'URL demandée sur ce serveur.

**Comment by alexkipar** [comment]
@whogarden are you signed in to the same account in the Play Store as the email you used to register for beta?

**Comment by whogarden** [comment]
No, the email of the play store is a gmail and the email for beta is laposte.fr

**Comment by alexkipar** [comment]
@whogarden can you provide the Gmail email?

**Comment by whogarden** [comment]
Email : espouare@gmail.com

**Comment by alexkipar** [comment]
@whogarden I've added that email and removed your comment with it. Please recheck that link on your smartphone - it should work now

**Comment by whogarden** [comment]
I got it Thank you
