### ISSUE TITLE
There is a running shipment with this original product

### ISSUE THREAD

**Issue by whogarden** [blynkkk/beta#75]
I receive that error when I try to start shipping.
(shipping previous firmware was ok with V 0.1.1)
Build:4:08 PM Today
Version:0.1.2
Type:TMPLy7SjT90M
Hardware:ESP32
MD5 Checksum:7086AEADF401AE5E9967F542FF6472A4
and No condition

**Comment by doom369** [comment]
@whogarden what status does that shipment has?

**Comment by whogarden** [comment]
I just see now that I can not have a shipment with my second device.
I have not seen that I can not chose the second device, it's not in the list.

**Comment by whogarden** [comment]
That's OK

**Comment by whogarden** [comment]
I understand that I must "cancel" the previous shipment of the same device (event if the update has been done)
to be able to make a new shipment.
Is this correct?

**Comment by whogarden** [comment]
In "Devices for new shipping" 
Shipment status is "Success" and status is "Online"
In "Blynk.Air" 
Status is "Live" with a green point blinking

Why not "Finished"?
