### ISSUE TITLE
How can I delete a template

### ISSUE THREAD

**Issue by whogarden** [blynkkk/beta#77]
Because of many manipulations I end up with a lot of templates and I don't know how to delete some of them?
What can I do?

**Comment by doom369** [comment]
You need to click on the template on the web, then the edit button in the right corner, and then "delete" button in the top right corner.

**Comment by whogarden** [comment]
There is no "delete" button, I have only "Save" and "Cancel"
![3](https://user-images.githubusercontent.com/16666934/118375781-37d73400-b5c4-11eb-99c3-af8aa8604a45.jpg)

**Comment by whogarden** [comment]
There is no "delete" button, I have only "Save" and "Cancel"
![3](https://user-images.githubusercontent.com/16666934/118375781-37d73400-b5c4-11eb-99c3-af8aa8604a45.jpg)

**Comment by whogarden** [comment]
I'm sorry, 
I found it (it's at the left of "Cancel")

**Comment by whogarden** [comment]
I can now see distinctly the delete button.
thank you for your wonderful involvement
