### ISSUE TITLE
Unable to scroll widget setting on tablet

### ISSUE THREAD

**Issue by thomoray** [blynkkk/beta#8]
Tablet Samsung S6 lite Android 11

When trying to setup widget settings in landscape on the tablet the settings do no scroll and just shudder in place.

Steps to reproduce
Turn the device to landscape view
Go to developer mode in the app
Select a device
Add a button
Tap on the button and try scrolling down to settings below the fold.

**Comment by doom369** [comment]
@thomoray thanks for the report! @alexkipar Please take a look.

**Comment by alexkipar** [comment]
@thomoray it should scroll. but not by the empty side of the screen

**Comment by alexkipar** [comment]
@thomoray can't reproduce it, can you attach a video?

**Comment by thomoray** [comment]
@alexkipar please close this ticket I have tried many different ways but I am also not able to reproduce.

**Comment by alexkipar** [comment]
@thomoray got it, it may be some ANR type of issue - I will check the performance logs from play store. thanks.
