### ISSUE TITLE
Questions about Legacy Blynk

### ISSUE THREAD

**Issue by JimE007** [blynkkk/beta#86]
Not an Issue - but not certain if there is some forum I should be using.

I have a few questions about the Legacy Blynk systems moving forward.  This is both to inform others that I have directed towards blynk in the past - and to address questions at an upcoming IoT presentation.   Also for personal reasons :-).

1) My understanding is that the Legacy Blynk Server will be shutdown at some point in the future.  Any rough estimate - 6 months - year - ???.
2) For an iphone -- Will the existing (legacy blynk App) be able to remain and coexist with the New Blynk App once it is officially released (i.e.  want to know if  the New App will  delete or over-write the legacy app)?
3) Currently I use a local server and have a couple dozen devices available for the kids to play with and to give the wife some fun "toys".  IF I wanted to migrate to the "new blynk" my understanding is the FREE allows 5 devices - otherwise I am faced with $400+/mon.   Two sub-questions:
      a) Any chance of a local environment being possible - to support more devices?   Even with a reduced feature set?
      b) A more modest fee (like $10-$20/mon) to support 20-25 devices as a potential?
4) When will the New Blynk be officially released?  Again I am working on a presentation - and I would like to know what to tell the other IoTers.  

Thanks so much

**Comment by doom369** [comment]
> My understanding is that the Legacy Blynk Server will be shutdown at some point in the future. Any rough estimate - 6 months - year - ???.

Correct. I think ~1 year. But that is not yet decided. Could be changed in any direction.

> For an iphone -- Will the existing (legacy blynk App) be able to remain and coexist with the New Blynk App once it is officially released (i.e. want to know if the New App will delete or over-write the legacy app)?

Yes. The old app will still be available in the app store.

> Currently I use a local server and have a couple dozen devices available for the kids to play with and to give the wife some fun "toys".

I think for the local server owners nothing will be changed unless they want to use the new app/cloud.

> IF I wanted to migrate to the "new blynk" my understanding is the FREE allows 5 devices - otherwise I am faced with $400+/mon.

400$ is a white-label app plan. If you don't run any business that's plan is not for you.

> a) Any chance of a local environment being possible - to support more devices? Even with a reduced feature set?

No plans for that.

> b) A more modest fee (like $10-$20/mon) to support 20-25 devices as a potential?

Yes. The launch will be very soon. Prices will be published.

> When will the New Blynk be officially released? Again I am working on a presentation - and I would like to know what to tell the other IoTers.

Tomorrow. That's not a joke :).
