### ISSUE TITLE
Blynk Beta android smartphone app is no more working

### ISSUE THREAD

**Issue by whogarden** [blynkkk/beta#87]
Since about an hour, the android smarphone app is not working.
I have only three dots moving.
Is it the end of testing?

**Comment by doom369** [comment]
@whogarden we rolled out the new version. It requires a new mobile client's app / web (clear the cache).

iOS swill may not work. Android should work.

**Comment by whogarden** [comment]
Done,
What email must I fill?
Email of play store or email of web blynk.cloud?

**Comment by doom369** [comment]
@whogarden during the login? "email of web blynk.cloud"

**Comment by whogarden** [comment]
It's what I have done, but app stays on "Connecting"
(clear the cache was not enough to stop the points moving
I had to delete all datas... was it a mistake).

**Comment by doom369** [comment]
@whogarden is that Android app? What version do you have?
@alexkipar did you release the app with the Geo DNS support?

**Comment by alexkipar** [comment]
@doom369 Geo-DNS support app's version will be available at best tomorrow only

**Comment by whogarden** [comment]
Android 10QKQ1

**Comment by alexkipar** [comment]
@whogarden are you using the 1.1.0 apps' version?

**Comment by whogarden** [comment]
It's the Blynk Beta Version 1.1.0

**Comment by alexkipar** [comment]
@whogarden 1.1.1 version should be available in minutes - please try it, I suppose it should fix this issue

**Comment by whogarden** [comment]
It's OK.
 Thank you

**Comment by whogarden** [comment]
I think I may close the issue
