### ISSUE TITLE
Has the API changed? - now not working

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#88]
I've been running a script which pushes data to virtual pins of my test device using the external API since the beginning of beta testing.
Since 16:13 BST today this has been failing with the error:
`{"error":{"message":"Invalid token."}}`

My API call is:
`https://blynk.cloud/external/api/update?token=REDACTED&pin=v12&value=12.93%22`

Pete.

**Comment by doom369** [comment]
@Peterkn2001 you can try this host `fra1.blynk.cloud`. Should work for you. We just deployed the distributed setup (like we have in blynk 1.0). In future, we'll implement forwarding or redirect for API. So generic host could be used without region specific domain.

**Comment by Peterkn2001** [comment]
Thanks @doom369 that host works fine.

I guess the documentation here:
https://docs.blynk.io/en/https-api/update-virtual-datastream-value
needs to be updated.

Pete.

**Comment by doom369** [comment]
@Peterkn2001 agree
@Mark-Pan please update the doc. Add add `NOTE` section that right now URL may requires specific region host. We'll need to show it on UI somewher.

**Comment by Mark-Pan** [comment]
Added to each HTTP API article of the documentation.

**Comment by doom369** [comment]
Updated docs + added troubleshooting section. If we get many reports about this issue we are gonna implement request forwarding on the server-side to forward the request to the required region. Right now it may be not necessary. We'll see.
