### ISSUE TITLE
Website Feedback & pricing questions...

### ISSUE THREAD

**Issue by Peterkn2001** [blynkkk/beta#89]
Having seen the banner message about what's happening on 25th June, I took a look at Blynk.io and have a bit of feedback...

1) At the top of the https://blynk.io/pricing#plan-comparison page, the plans are listed left to right as Free, Pro, Plus but as you scroll down to the comparison of what's included, the sequence changes to Free, Plus, Pro.
Very confusing!

2) The cost of adding an additional device is quoted as "$4,99 per device" with a comma rather than a decimal point

3) There is no mention in the comparison of the "lower transaction cap" for the free version. How will this work?

4) There's no explanation of which widgets fall into the Basic and Pro categories. Are all of the "old" widgets available for free?

Pete.

**Comment by doom369** [comment]
Thanks for the feedback. I'll check these questions with the team.

**Comment by blynkkk** [comment]
Thanks Peter!

1. will fix
2. fixed
3. this will be defined by 25th
4. this info will be soon added to website and pricing pages
