### ISSUE TITLE
iOS App only shows dancing dots on white screen

### ISSUE THREAD

**Issue by jpecor** [blynkkk/beta#90]
I had some time to get back to testing the new Blynk app this morning, and all I get now is 3 dancing black dots on a white screen:

![IMG_B4D7BAC7DFFE-1](https://user-images.githubusercontent.com/14111408/119559482-58438300-bd68-11eb-9c1f-0fed0bc4153f.jpeg)

Any ideas?

Thanks!
Jason

**Comment by eepetrash** [comment]
Hi @jpecor 
Thats happening because the server started GeoDNS resolutions today and looks like your existing account resides in a different server to the one app connects now.

This will be addressed in the next iOS app update.

**Comment by jpecor** [comment]
Thanks @eepetrash!

Since I'm evaluating the app via TestFlight, will the update come through the same way as normal app updates?

**Comment by eepetrash** [comment]
@jpecor yes

**Comment by jpecor** [comment]
Good news.  Any idea on timeline?  No rush on my end - just want to keep an eye out for it.

**Comment by eepetrash** [comment]
The build, 3.1.1 (0) is sent to Testflight, but required Apple review. Usually it takes 1 or 2 days.

**Comment by jpecor** [comment]
Sounds good, thanks!
