### ISSUE TITLE
led widget not working correctly

### ISSUE THREAD

**Issue by rob-buckingham** [blynkkk/beta#91]
I have led widgets in my project and use the simple code led1.on(); and led1.off(); my datastream is set to double and  range 0 to 10000.
when using app version 3.10(23) everything is fine
when using app version 3.10(25) leds dont light up at all
when using app version 3.10(28) leds light up but very dim

I've also tried a very simple sketch that turns led on and off every second and had  the same results even when using  led1.setValue(value);

**Comment by doom369** [comment]
@rob-buckingham hello. Is that ios/android?

**Comment by rob-buckingham** [comment]
sorry forgot to mention ios

**Comment by eepetrash** [comment]
> led1.setValue(value);

@rob-buckingham what value are you sending, the 10000 (max value according to the datasrteam settings)?

**Comment by rob-buckingham** [comment]
Not sending a specific value just led1.on();
and led1.off();
But I get the same results when I send led1.setValue(255); or led1.setValue(0);
Also the colours on the led widgets are a very light grey not the colours I selected in widget settings for led

**Comment by rob-buckingham** [comment]
Changing datastream to range 0 to 255 fixes the issue so I’m not sure if this is solved as anyone can still replicate my setup and have the same results without any warning it won’t work correctly

**Comment by eepetrash** [comment]
OK, As agreed [before](https://github.com/blynkkk/blynk_Issues/issues/59), mobile apps work with the min/max defined in the datastreams settings.
