### ISSUE TITLE
Feature request mobile app: copy auth tokens with corresponding device name

### ISSUE THREAD

**Issue by jensdenbraber** [blynkkk/beta#92]
When you go to the project settings and click on the "Copy all" button of the auth tokens. Only the tokens are copied. It is unclear which token corresponds with which device. 

Proposal:

A structure something like:
{
  \<Device name>:\<Auth token>,
  \<Device name>:\<Auth token>,
  \<Device name>:\<Auth token>
}

**Comment by doom369** [comment]
@jensdenbraber you're talking about the mobile app, right?

**Comment by jensdenbraber** [comment]
> 
> 
> @jensdenbraber you're talking about the mobile app, right?

Yes, the Android mobile app in this case :)

**Comment by blynkkk** [comment]
should be moved out from mobile app and managed on the web

**Comment by alexkipar** [comment]
@blynkkk we do t have such functionality in the new app

**Comment by alexkipar** [comment]
@jensdenbraber is it about Blynk 2.28.x ?

**Comment by jensdenbraber** [comment]
It is version: 2.27.27 (15.04.2021 18:25:04) running on Android.

**Comment by alexkipar** [comment]
@jensdenbraber got it. i will add smth like the proposed logic for clipboard copy of tokens in one of next updates
