### ISSUE TITLE
Can't download report

### ISSUE THREAD

**Issue by whogarden** [blynkkk/beta#93]
When I try to "download report", I have the error : 
Failure: 404 Not Found

**Comment by doom369** [comment]
@whogarden yeah, we I saw this error in the logs. Already fixed, will be available with next deploy.

**Comment by doom369** [comment]
@whogarden fixed. Please reopen is reproduced.

**Comment by whogarden** [comment]
When I click on "Download", the file is 
https://blynk.cloud/device_data_349_2021-05-31T04-13-36-250.zip
I have : 
Failure: 404 Not Found

**Comment by Mark-Pan** [comment]
****ENV:****
Firefox 88.0.1 (64-bit)
Edge Версия 91.0.864.37 (Официальная сборка) (64-разрядная версия)

****AR:****
UI shows an attempt to upload the file
.bin is not uploaded
no UI or console errors
![upload ota](https://user-images.githubusercontent.com/67413917/120287074-904a4900-c2c7-11eb-8f88-bf1666d37c8f.PNG)

**Comment by doom369** [comment]
@whogarden fixed.

**Comment by whogarden** [comment]
Download is successfully done.
