### ISSUE TITLE
 Choosing 3 Labels tile design creates UI error

### ISSUE THREAD

**Issue by rmznsy** [blynkkk/beta#94]
After you create a template in web app than, on mobile app (Android S10e) when you choose 3 Labels tile design, it does not work properly.
This one is before the change.
![Screenshot_20210526-174624_Blynk IoT](https://user-images.githubusercontent.com/81516108/119682560-a7161900-be4b-11eb-8a18-90942fd73bca.jpg)

These are after you choose the 3 Labels design.

![Screenshot_20210526-174715_Blynk IoT](https://user-images.githubusercontent.com/81516108/119682639-b7c68f00-be4b-11eb-98de-bdaf78049913.jpg)
![Screenshot_20210526-175052_Blynk IoT](https://user-images.githubusercontent.com/81516108/119682645-b8f7bc00-be4b-11eb-889c-ed5ad1115c7a.jpg)

**Comment by alexkipar** [comment]
@rmznsy.

We will upload a fix today, I hope it will be available soon

**Comment by alexkipar** [comment]
@rmznsy 
The fix should be available, but you should recreate that template or use it as 8 columns one ))

**Comment by doom369** [comment]
@rmznsy closing. Please reopen if not fixed.
