### ISSUE TITLE
Web dashboard ignores empty space

### ISSUE THREAD

**Issue by rmznsy** [blynkkk/beta#95]
On web dashboard, when you leave a space on top of a widget, after you save the dashboard, it goes up. It does not allow white space in UI design. (Mac Os 11.3.1, Firefox 88.0.1)

This is editing page.
![Screen Shot 2021-05-26 at 18 40 47](https://user-images.githubusercontent.com/81516108/119689940-f2332a80-be51-11eb-8353-5bd347215e0b.png)

This is after you save.
![Screen Shot 2021-05-26 at 18 40 55](https://user-images.githubusercontent.com/81516108/119690038-04ad6400-be52-11eb-9939-8ea769c4db4a.png)

**Comment by doom369** [comment]
@rmznsy the issue was fixed. Please reopen if not.
