### ISSUE TITLE
Can't upload file in Blynk.Air

### ISSUE THREAD

**Issue by whogarden** [blynkkk/beta#98]
I can not upload file.bin in Blynk.air
I click on Upload firmware file (.bin, .tar, .zip)
Then I select the .bin
I have the message "Uploading file..."
But no firmware appears.
According to bug #79
"This is intended. If you select no devices, a "Live" upgrade is created.
Which means, all of the devices (i.e. even newly added) of selected product will be upgraded"
I have no device selected.

**Comment by EarlOld** [comment]
@whogarden Can you provide your **.bin** file?

**Comment by whogarden** [comment]
.bin is there 
https://1drv.ms/u/s!AumeH7O_5gYEqsxfI1SIrhkcIHbNWg?e=7pd5to

**Comment by doom369** [comment]
The issue is reproduced, Thanks. Will be fixed today.

**Comment by doom369** [comment]
@whogarden the issue is fixed. Please reopen if not fixed.

**Comment by whogarden** [comment]
Not working.

**Comment by doom369** [comment]
@whogarden did you refresh the page? Do you see some errors in the browser console?

**Comment by whogarden** [comment]
I logged out.
And then log in.

**Comment by doom369** [comment]
@whogarden could you please open the web in the new tab instead of logout/login? In order to get the latest "UI", the page need to be fully refreshed.

**Comment by whogarden** [comment]
Sorry,
What do you mean by new tab.
I just tap "F5"

**Comment by doom369** [comment]
@whogarden yes. I mean F5. So no luck? Do you see some errors?

**Comment by whogarden** [comment]
I can only see "Uploading file..." and then nothing.

**Comment by doom369** [comment]
@whogarden we would need the web browser console output. As I can't reproduce.

**Comment by whogarden** [comment]
I think I have an answer
It's not working with firefox, but I can work with Chrome.

**Comment by doom369** [comment]
Hm... I see. We will check with the firefox. Thanks.

**Comment by whogarden** [comment]
I shipping is done, but the device restarts but can not connect to blynk 
Error [8735] Content-Length not defined
I used the same bin "RS0_ESP8266-255.ino.generic.bin"

**Comment by doom369** [comment]
@vshymanskyy please take a look.

**Comment by whogarden** [comment]
Serial output if it can help.
[Can't upload file in Blynk.Air #98.txt](https://github.com/blynkkk/blynk_Issues/files/6570875/Can.t.upload.file.in.Blynk.Air.98.txt)

**Comment by doom369** [comment]
@whogarden thanks. This one is geo dns issue. We right now generate generic url "blynk.cloud", but we need to generate "fra1.blynk.cloud". It is already fixed, but requires extensive testing. Hopefully will do deploy at the end of this week.

**Comment by whogarden** [comment]
What can I do with error "Content-Length not defined"
1. Reflash does nothing more
2. Hold the button to reset configuration... doesn't work
Device is seen registered in the mobile app, but (Can't connect the device)

**Comment by whogarden** [comment]
The state of the shipping is 
State live and progress grey
I cancel the shipping, 
and the device has connected and is now OK

**Comment by doom369** [comment]
@whogarden fixed.

**Comment by whogarden** [comment]
As it is written in documentation "Updating Firmware Over-The-Air" 
"Otherwise leave the selection empty"
I leave the device selection empty.
The .bin is uploaded, the device is updated, restarts and is OK
But, as I already wrote in issue #79,
The status of the shipment stays live with the green dot blinking.
And we can not see if the update is finished (the device can be far away from my location)
We are unable to download the report because this "action" is not in the list.

(May I suggest you do not allow "Start Shipping" if no device is selected)

**Comment by doom369** [comment]
> The status of the shipment stays live with the green dot blinking.

That's correct. When you do not select any device - that's an ongoing (never ending) shipment. This is because when you sell your devices and want them to update as soon they connect - you don't know when the device will be added (purchased, delivered, unpacked). So this is an ongoing shipment and is designed for this use case.

If you want the shipment to finish, you need to select specific device to apply the update to.

> And we can not see if the update is finished (the device can be far away from my location)

You can click on a shipment. Than click on specific device and you'll get full report for it.

> We are unable to download the report because this "action" is not in the list.

Year, the button is missing, it's a bug.

**Comment by whogarden** [comment]
Thank you. 
(I begin to understand...)
I did not think I would find the shipment events there.
Yes if we can download a report it will be clear.

**Comment by whogarden** [comment]
OK thank you
