### ISSUE TITLE
Minimum size of charts are now too long

### ISSUE THREAD

**Issue by whogarden** [blynkkk/beta#99]
I don't know if a made something unexpected, but with previous minimum size of charts, I could set 2 charts side to side like : 
![Previous_size](https://user-images.githubusercontent.com/16666934/119820734-18a8a280-bef2-11eb-93e5-07202a653e39.jpg)
But now with the minimum size, I can only set one chart the second is dropped under.
![Now_size](https://user-images.githubusercontent.com/16666934/119821030-63c2b580-bef2-11eb-9ee1-a3299dd4fafe.jpg)
And if I touch an old chart, it' size grows and can not be set to it's previous size.

**Comment by doom369** [comment]
@whogarden the issue is fixed. thanks for the report. It appears it was a design bug :). Please reopen if not.

**Comment by whogarden** [comment]
Charts now auto resize by themself
[Capturer-01.zip](https://github.com/blynkkk/blynk_Issues/files/6570709/Capturer-01.zip)

**Comment by doom369** [comment]
@whogarden fixed.

**Comment by whogarden** [comment]
It's OK.
